const {webkit,devices}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await webkit.launch({headless:true});
 const context=await browser.newContext({...devices['iPad (gen 7)']});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.GAMES_URL||'http://127.0.0.1:8765';
 await page.goto(base+'/games/');
 const links=await page.locator('.card').evaluateAll(a=>a.map(x=>x.getAttribute('href')));assert.equal(links.length,20);assert.equal(new Set(links).size,20);
 for(const url of links){await page.goto(base+url);await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,url+' overflow');const mode=page.locator('#mode');if(await mode.count()&&url.includes('/games/')&&!url.includes('neon-dash')){for(const v of ['0','1','2']){await mode.selectOption(v);assert.ok(await page.locator('#board').textContent()!==null);await page.locator('#new').tap()}}console.log('OPEN',url)}
 await page.goto(base+'/games/neon-snake/');await page.locator('#start').tap();await page.waitForTimeout(2100);assert.equal(await page.evaluate(()=>dead),true);await page.locator('#start').tap();assert.equal(await page.evaluate(()=>dead),false);await page.locator('[data-d="u"]').tap();await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>dir.y),-1);
 await page.goto(base+'/games/memory-grid/');await page.locator('#start').tap();page.once('dialog',d=>d.accept());await page.locator('#reset').tap();await page.waitForTimeout(2800);assert.equal(await page.evaluate(()=>locked),true);assert.equal(await page.locator('#start').isEnabled(),true);assert.equal(await page.locator('.on').count(),0);await page.locator('#start').tap();await page.waitForTimeout(2800);const sequence=await page.evaluate(()=>need.slice());for(const i of sequence)await page.locator('.cell').nth(i).tap();assert.equal(await page.locator('#level').textContent(),'2');
 await page.goto(base+'/games/neon-dash/');await page.locator('#start').tap();await page.locator('#jump').dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch'});await page.waitForTimeout(200);await page.locator('#pause').tap();assert.equal(await page.locator('#title').textContent(),'Ta en pust.');await page.locator('#start').tap();await page.waitForTimeout(5500);assert.equal(await page.locator('#start').textContent(),'SPILL IGJEN ↗');await page.locator('#start').tap();assert.equal(await page.locator('#score').textContent(),'0');
 await page.goto(base+'/games/connect-four/');await page.locator('#board button').nth(35).tap();await page.waitForTimeout(500);assert.equal(await page.locator('.gold').count(),1);assert.equal(await page.locator('.red').count(),1);
 await page.goto(base+'/games/mine-lab/');await page.locator('#board button').nth(27).tap();assert.ok(await page.locator('.revealed').count()>0);assert.ok(!(await page.locator('#status').textContent()).includes('En mine'));await page.locator('#actions button').tap();const closed=page.locator('#board button:not(.revealed)').first();await closed.tap();assert.equal(await page.locator('#board').getByText('⚑',{exact:true}).count(),1);
 await page.goto(base+'/games/merge-2048/');for(const key of ['ArrowDown','ArrowLeft','ArrowDown','ArrowRight'])await page.keyboard.press(key);assert.ok(await page.locator('[data-value]:not([data-value="0"])').count()>=2);
 await page.goto(base+'/games/slide-puzzle/');let vals=await page.locator('#board button').allTextContents(),empty=vals.indexOf(''),neighbor=empty%4?empty-1:empty+1;await page.locator('#board button').nth(neighbor).tap();assert.ok((await page.locator('#stat').textContent()).startsWith('1 trekk'));
 await page.goto(base+'/games/code-breaker/');await page.locator('input').fill('0012');await page.locator('form button').tap();assert.equal(await page.locator('.code-row').count(),0);await page.locator('input').fill('0123');await page.locator('form button').tap();assert.equal(await page.locator('.code-row').count(),1);
 await page.goto(base+'/games/word-hunt/');const letters=await page.locator('#board button').allTextContents(),words=await page.locator('.wordlist span').allTextContents(),n=8;for(const word of words){let found=false;for(let i=0;i<n*n&&!found;i++)for(const [dr,dc]of[[0,1],[1,0],[1,1],[-1,1],[0,-1],[-1,0],[-1,-1],[1,-1]]){const ids=Array.from(word,(_,k)=>[Math.floor(i/n)+k*dr,i%n+k*dc]);if(ids.every(([r,c],k)=>r>=0&&r<n&&c>=0&&c<n&&letters[r*n+c]===word[k])){await page.locator('#board button').nth(i).tap();const [r,c]=ids.at(-1);await page.locator('#board button').nth(r*n+c).tap();found=true;break}}assert.ok(found,word)}assert.equal(await page.locator('.found').count(),words.length);
 await page.goto(base+'/games/maze-run/');const maze=await page.locator('#board .cell').evaluateAll(a=>a.map(x=>x.className)),size=15,start=maze.findIndex(s=>s.includes('player')),end=maze.findIndex(s=>s.includes('exit'));const q=[start],paths=new Map([[start,[]]]);for(let k=0;k<q.length&&!paths.has(end);k++){let i=q[k];for(const [d,delta]of [['ArrowUp',-size],['ArrowDown',size],['ArrowLeft',-1],['ArrowRight',1]]){let j=i+delta;if(j>=0&&j<maze.length&&!maze[j].includes('wall')&&!paths.has(j)){paths.set(j,[...paths.get(i),d]);q.push(j)}}}assert.ok(paths.has(end));for(const d of paths.get(end))await page.keyboard.press(d);assert.match(await page.locator('#status').textContent(),/fant utgangen/);
 await page.goto(base+'/games/target-rush/');await page.locator('#actions button').tap();await page.locator('.target:not(.decoy)').dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch'});assert.match(await page.locator('#stat').textContent(),/^10 poeng/);await page.locator('#new').tap();assert.equal(await page.locator('.target').count(),0);
 // Solve an actual generated sudoku through visible controls.
 await page.goto(base+'/games/sudoku-lab/');let values=(await page.locator('#board button').allTextContents()).map(Number);const initial=values.slice();function solve(){let i=values.indexOf(0);if(i<0)return true;for(let v=1;v<=6;v++){if(values.some((x,j)=>x===v&&(Math.floor(j/6)===Math.floor(i/6)||j%6===i%6||Math.floor(j/12)===Math.floor(i/12)&&Math.floor(j%6/3)===Math.floor(i%6/3))))continue;values[i]=v;if(solve())return true;values[i]=0}return false}assert.ok(solve());for(let i=0;i<36;i++)if(!initial[i]){await page.locator('#board button').nth(i).tap();await page.locator('#actions button').nth(values[i]-1).tap()}assert.match(await page.locator('#status').textContent(),/Løst!/);
 // Lights Out solved by row-chasing, enumerating first-row choices.
 await page.goto(base+'/games/lights-out/');const lights=await page.locator('#board button').evaluateAll(a=>a.map(x=>x.classList.contains('on')));let answer;for(let mask=0;mask<32&&!answer;mask++){const a=lights.slice(),press=[];function flip(i){press.push(i);for(const j of [i,i%5?i-1:-1,i%5<4?i+1:-1,i-5,i+5])if(j>=0&&j<25)a[j]=!a[j]}for(let c=0;c<5;c++)if(mask&(1<<c))flip(c);for(let r=1;r<5;r++)for(let c=0;c<5;c++)if(a[(r-1)*5+c])flip(r*5+c);if(!a.some(Boolean))answer=press}assert.ok(answer);for(const i of answer)await page.locator('#board button').nth(i).tap();assert.match(await page.locator('#status').textContent(),/Alle lys/);
 fs.mkdirSync('/tmp/ians-games-qa',{recursive:true});await page.goto(base+'/games/');await page.screenshot({path:'/tmp/ians-games-qa/catalog-ipad.png',fullPage:true});await page.goto(base+'/games/neon-dash/');await page.screenshot({path:'/tmp/ians-games-qa/neon-dash-ipad.png'});
 await page.setViewportSize({width:1024,height:768});for(const slug of ['ians-orbit','ian-the-adventure']){await page.goto(base+'/games/'+slug+'/');assert.equal(await page.locator('.mobile-controls').isVisible(),true)}
 await page.setViewportSize({width:390,height:844});for(const url of links){await page.goto(base+url);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,url+' phone overflow')}
 assert.deepEqual(errors,[]);console.log('PASS: 20 pages, 30 mode/reset combinations, touch, game rules, restart, portrait/landscape and mobile overflow.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
