const { TableClient } = require('@azure/data-tables');
const crypto = require('crypto');
const { hasAccess } = require('../sameie-access/index.js');
const TABLE='IansYearWheel',SAMEIE='straumsfjellet-panorama';
const BOARD_POLICY='Styremedlemmer har møteplikt. Dersom noe kommer i veien, meldes avbud i forkant. Varamedlemmer har ingen møteplikt, men kan møte om ønskelig. Styret trenger minst 3 deltakere for å gjennomføre møtet. Dersom ordinære styremedlemmer ikke kan møte, kan varamedlemmer bli kalt inn.';
const BOARD_RECIPIENTS=['henrik.bergfjord@outlook.com','camilla.michelsen@helse-bergen.no','aofo@outlook.com','aneberg61@gmail.com','gunnlaugssongunnlaugur@gmail.com','nuduap@gmail.com','hauglab0@gmail.com'];
const BOARD_MEETINGS=['2026-09-24','2026-10-29','2026-11-26','2026-12-30','2027-01-28','2027-02-25','2027-03-25'];
function json(status,body){return{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'},body};}
function clean(v,max){return String(v||'').trim().slice(0,max);}
function principal(req){try{const raw=req.headers['x-ms-client-principal'];if(!raw)return null;return JSON.parse(Buffer.from(raw,'base64').toString('utf8'));}catch{return null;}}
function client(){const cs=process.env.IANS_BOOKING_STORAGE||process.env.AzureWebJobsStorage;if(!cs)throw new Error('Storage is not configured');return TableClient.fromConnectionString(cs,TABLE);}
function actor(p){return clean((p&&p.userDetails)||'',254)||'Microsoft-bruker';}
function recipients(v,email){let a=[];if(Array.isArray(v))a=v;else if(v)a=String(v).split(/[;,\n]+/);if(email)a.push(email);return [...new Set(a.map(x=>clean(x,254).toLowerCase()).filter(x=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)))].slice(0,25);}
function out(e){return{id:e.rowKey,title:e.title,date:e.date,startTime:e.startTime||'',endTime:e.endTime||'',allDay:e.allDay!==false,category:e.category,notes:e.notes,annual:!!e.annual,systemNotify:e.systemNotify!==false,notifyDays:Number(e.notifyDays||0),email:e.email||'',recipients:recipients(e.recipients,e.email),status:e.status||'active',createdAt:e.createdAt||'',createdBy:e.createdBy||'',updatedAt:e.updatedAt||'',updatedBy:e.updatedBy||'',lastNotifiedAt:e.lastNotifiedAt||'',systemDefault:!!e.systemDefault};}
function defaultMeetings(){return BOARD_MEETINGS.map((date,i)=>({id:'board-'+date,rowKey:'board-'+date,title:'Styremøte',date,startTime:'17:00',endTime:'19:00',allDay:false,category:'Styremøte',notes:BOARD_POLICY,annual:false,systemNotify:true,notifyDays:2,email:BOARD_RECIPIENTS[0],recipients:BOARD_RECIPIENTS,status:'active',createdAt:'2026-09-12T00:00:00.000Z',createdBy:'Straumsfjellet Panorama',updatedAt:'2026-09-12T00:00:00.000Z',updatedBy:'Straumsfjellet Panorama',systemDefault:true,sort:i}));}
module.exports=async function(context,req){try{const p=principal(req);if(!p)return context.res=json(401,{ok:false,error:'Ikke innlogget.'});const who=actor(p).toLowerCase(),access=await hasAccess(who,SAMEIE,'yearwheel');if(!access.approved)return context.res=json(403,{ok:false,error:'Du har ikke godkjent styretilgang til årshjulet.',accessRequired:true});const c=client();await c.createTable().catch(()=>{});const pk=SAMEIE;
if(req.method==='GET'){const items=[];for await(const e of c.listEntities({queryOptions:{filter:`PartitionKey eq '${pk}'`}})){items.push(out(e));}const existing=new Set(items.map(x=>x.date+'|'+x.title.toLowerCase()));for(const m of defaultMeetings())if(!existing.has(m.date+'|styremøte'))items.push(m);items.sort((a,b)=>String(a.date+a.startTime).localeCompare(String(b.date+b.startTime)));return context.res=json(200,{ok:true,items,user:p.userDetails||'',sameie:'Straumsfjellet Panorama Sameie',boardReminderPolicy:{days:2,recipients:BOARD_RECIPIENTS,policy:BOARD_POLICY}});}
if(req.method==='POST'){const b=req.body||{},title=clean(b.title,160),date=clean(b.date,10),category=clean(b.category,50)||'Oppgave',notes=clean(b.notes,2000),email=clean(b.email,254),startTime=clean(b.startTime,5),endTime=clean(b.endTime,5),allDay=b.allDay!==false,annual=!!b.annual,systemNotify=b.systemNotify!==false,notifyDays=systemNotify?Math.max(0,Math.min(365,Number(b.notifyDays||0))):0,to=recipients(b.recipients,email);if(title.length<2||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(date))return context.res=json(400,{ok:false,error:'Tittel og gyldig dato må fylles ut.'});const now=new Date().toISOString(),by=actor(p),entity={partitionKey:pk,rowKey:crypto.randomUUID(),title,date,startTime:allDay?'':startTime,endTime:allDay?'':endTime,allDay,category,notes,email:to[0]||'',recipients:to.join(';'),annual,systemNotify,notifyDays,status:'active',createdAt:now,createdBy:by,updatedAt:now,updatedBy:by};await c.createEntity(entity);return context.res=json(201,{ok:true,item:out(entity)});}
if(req.method==='PUT'){const b=req.body||{},id=clean((req.query&&req.query.id)||b.id,80);if(!id)return context.res=json(400,{ok:false,error:'Mangler id.'});if(id.startsWith('board-'))return context.res=json(409,{ok:false,error:'Fast styremøte endres i møteplanen, ikke som enkeltaktivitet.'});const e=await c.getEntity(pk,id);for(const k of ['title','date','category','notes','email','startTime','endTime','status'])if(Object.prototype.hasOwnProperty.call(b,k))e[k]=clean(b[k],k==='notes'?2000:k==='email'?254:160);if(Object.prototype.hasOwnProperty.call(b,'recipients')){const to=recipients(b.recipients,b.email);e.recipients=to.join(';');e.email=to[0]||'';}if(Object.prototype.hasOwnProperty.call(b,'annual'))e.annual=!!b.annual;if(Object.prototype.hasOwnProperty.call(b,'allDay'))e.allDay=!!b.allDay;if(Object.prototype.hasOwnProperty.call(b,'systemNotify'))e.systemNotify=!!b.systemNotify;if(Object.prototype.hasOwnProperty.call(b,'notifyDays'))e.notifyDays=Math.max(0,Math.min(365,Number(b.notifyDays||0)));e.updatedAt=new Date().toISOString();e.updatedBy=actor(p);await c.updateEntity(e,'Replace');return context.res=json(200,{ok:true,item:out(e)});}
if(req.method==='DELETE'){const id=clean(req.query&&req.query.id,80);if(!id)return context.res=json(400,{ok:false,error:'Mangler id.'});if(id.startsWith('board-'))return context.res=json(409,{ok:false,error:'Fast styremøte kan ikke slettes her.'});await c.deleteEntity(pk,id);return context.res=json(200,{ok:true});}
context.res=json(405,{ok:false,error:'Metode ikke støttet.'});}catch(e){context.log.error(e);context.res=json(500,{ok:false,error:'Årshjulet kunne ikke behandles akkurat nå.'});}};