const { TableClient } = require('@azure/data-tables');
const crypto = require('crypto');
const TABLE='IansYearWheel';
function json(status,body){return{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'},body};}
function clean(v,max){return String(v||'').trim().slice(0,max);}
function principal(req){try{const raw=req.headers['x-ms-client-principal'];if(!raw)return null;return JSON.parse(Buffer.from(raw,'base64').toString('utf8'));}catch{return null;}}
function client(){const cs=process.env.IANS_BOOKING_STORAGE||process.env.AzureWebJobsStorage;if(!cs)throw new Error('Storage is not configured');return TableClient.fromConnectionString(cs,TABLE);}
function partitionFor(p){const id=(p&&p.userId)||'unknown';return crypto.createHash('sha256').update(id).digest('hex').slice(0,40);}
module.exports=async function(context,req){try{const p=principal(req);if(!p)return context.res=json(401,{ok:false,error:'Ikke innlogget.'});const c=client();await c.createTable().catch(()=>{});const pk=partitionFor(p);if(req.method==='GET'){const items=[];for await(const e of c.listEntities({queryOptions:{filter:`PartitionKey eq '${pk}'`}})){items.push({id:e.rowKey,title:e.title,date:e.date,category:e.category,notes:e.notes,annual:!!e.annual,notifyDays:Number(e.notifyDays||0),email:e.email||'',createdAt:e.createdAt});}items.sort((a,b)=>String(a.date).localeCompare(String(b.date)));return context.res=json(200,{ok:true,items,user:p.userDetails||''});}
if(req.method==='POST'){const b=req.body||{};const title=clean(b.title,160),date=clean(b.date,10),category=clean(b.category,50)||'Oppgave',notes=clean(b.notes,1500),email=clean(b.email,254),annual=!!b.annual,notifyDays=Math.max(0,Math.min(365,Number(b.notifyDays||0)));if(title.length<2||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(date))return context.res=json(400,{ok:false,error:'Tittel og gyldig dato må fylles ut.'});const now=new Date().toISOString();const entity={partitionKey:pk,rowKey:crypto.randomUUID(),title,date,category,notes,email,annual,notifyDays,createdAt:now,updatedAt:now};await c.createEntity(entity);return context.res=json(201,{ok:true,item:{id:entity.rowKey,title,date,category,notes,email,annual,notifyDays,createdAt:now}});}
if(req.method==='DELETE'){const id=clean(req.query&&req.query.id,80);if(!id)return context.res=json(400,{ok:false,error:'Mangler id.'});await c.deleteEntity(pk,id);return context.res=json(200,{ok:true});}
context.res=json(405,{ok:false,error:'Metode ikke støttet.'});}catch(e){context.log.error(e);context.res=json(500,{ok:false,error:'Årshjulet kunne ikke behandles akkurat nå.'});}};