const { EmailClient } = require('@azure/communication-email');
const { hasAccess } = require('../sameie-access/index.js');
const SAMEIE='straumsfjellet-panorama';
function json(status,body){return{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'},body};}
function principal(req){try{const raw=req.headers['x-ms-client-principal'];if(!raw)return null;return JSON.parse(Buffer.from(raw,'base64').toString('utf8'));}catch{return null;}}
function clean(v,max){return String(v||'').trim().slice(0,max)}
function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function validEmails(v){const a=Array.isArray(v)?v:String(v||'').split(/[;,\n]+/);return [...new Set(a.map(x=>clean(x,254).toLowerCase()).filter(x=>/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i.test(x)))].slice(0,25)}
function icsEscape(v){return String(v||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function eventIcs(e){const d=String(e.date||'').replace(/-/g,''),start=String(e.startTime||'17:00').replace(':','')+'00',end=String(e.endTime||'19:00').replace(':','')+'00';return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//IANS//Sameie//NO','METHOD:REQUEST','BEGIN:VEVENT',`UID:${clean(e.id||e.date,100)}@ians.no`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z')}`,`DTSTART;TZID=Europe/Oslo:${d}T${start}`,`DTEND;TZID=Europe/Oslo:${d}T${end}`,`SUMMARY:${icsEscape(e.title||'Styremøte')}`,`DESCRIPTION:${icsEscape(e.notes||'')}`,'END:VEVENT','END:VCALENDAR'].join('\r\n')}
module.exports=async function(context,req){try{const p=principal(req);if(!p)return context.res=json(401,{ok:false,error:'Ikke innlogget.'});const email=clean(p.userDetails,254).toLowerCase(),access=await hasAccess(email,SAMEIE,'yearwheel');if(!access.approved)return context.res=json(403,{ok:false,error:'Du har ikke godkjent styretilgang.'});const cs=process.env.COMMUNICATION_SERVICES_CONNECTION_STRING;const sender=process.env.IANS_EMAIL_SENDER||process.env.ACADEMY_EMAIL_SENDER;if(!cs||!sender)return context.res=json(503,{ok:false,error:'Azure e-post er ikke konfigurert ennå.'});const b=req.body||{},client=new EmailClient(cs);
if(b.mode==='event'){const e=b.event||{},to=validEmails(b.recipients||e.recipients);if(!to.length)return context.res=json(400,{ok:false,error:'Ingen gyldige mottakere.'});const when=`${clean(e.date,10)}${e.startTime?' kl. '+clean(e.startTime,5):''}`;const plain=`${e.title||'Styremøte'}\n\n${when}\n\n${e.notes||''}\n\nDette varselet er sendt fra IANS Sameie via Azure.`;const html=`<div style="font-family:Arial,sans-serif;max-width:720px"><h1>${esc(e.title||'Styremøte')}</h1><p><strong>${esc(when)}</strong></p><p style="white-space:pre-line">${esc(e.notes||'')}</p><p style="color:#777;font-size:12px">Sendt fra IANS Sameie via Azure.</p></div>`;const ics=Buffer.from(eventIcs(e),'utf8').toString('base64');const poller=await client.beginSend({senderAddress:sender,content:{subject:`${e.title||'Styremøte'} · ${clean(e.date,10)}`,plainText:plain,html},recipients:{to:to.map(address=>({address}))},attachments:[{name:'moteinvitasjon.ics',contentType:'text/calendar; method=REQUEST',contentInBase64:ics}]});const result=await poller.pollUntilDone();return context.res=json(200,{ok:true,status:result.status||'sent',sentTo:to.length,sender});}
const to=validEmails(b.to);if(!to.length)return context.res=json(400,{ok:false,error:'Ugyldig e-postadresse.'});const year=Number(b.year)||new Date().getFullYear();const all=[...(Array.isArray(b.items)?b.items:[]).map(x=>({date:clean(x.date,10),title:clean(x.title,160),category:clean(x.category,60)||'Oppgave',notes:clean(x.notes,800)})),...(Array.isArray(b.holidays)?b.holidays:[]).map(x=>({date:clean(x.date,10),title:clean(x.title,160),category:'Helligdag',notes:''}))].sort((a,b)=>a.date.localeCompare(b.date));const plain=['IANS Årshjul '+year,'',...all.map(x=>`${x.date} · ${x.title} · ${x.category}${x.notes?' · '+x.notes:''}`),'','Sendt fra IANS Årshjul via Azure.'].join('\n');const rows=all.map(x=>`<tr><td style="padding:8px;border-bottom:1px solid #ddd">${esc(x.date)}</td><td style="padding:8px;border-bottom:1px solid #ddd"><strong>${esc(x.title)}</strong><br><span style="color:#666">${esc(x.category)}${x.notes?' · '+esc(x.notes):''}</span></td></tr>`).join('');const html=`<div style="font-family:Arial,sans-serif;max-width:760px;margin:auto"><h1>IANS Årshjul ${year}</h1><p>Årsplan med aktiviteter og norske helligdager.</p><table style="width:100%;border-collapse:collapse">${rows}</table><p style="color:#777;font-size:12px;margin-top:24px">Sendt fra IANS Årshjul via Azure.</p></div>`;const poller=await client.beginSend({senderAddress:sender,content:{subject:`IANS Årshjul ${year}`,plainText:plain,html},recipients:{to:to.map(address=>({address}))}});const result=await poller.pollUntilDone();context.res=json(200,{ok:true,status:result.status||'sent',sentTo:to.length,sender});}catch(e){context.log.error(e);context.res=json(500,{ok:false,error:'Kunne ikke sende e-post fra Azure akkurat nå.'});}};