const { TableClient } = require('@azure/data-tables');
const crypto=require('crypto');
const TABLE='IansYearWheel';
function principal(req){try{const raw=req.headers['x-ms-client-principal'];if(!raw)return null;return JSON.parse(Buffer.from(raw,'base64').toString('utf8'));}catch{return null;}}
function storage(){const cs=process.env.IANS_BOOKING_STORAGE||process.env.AzureWebJobsStorage;if(!cs)throw new Error('Storage is not configured');return TableClient.fromConnectionString(cs,TABLE);}
function partitionFor(p){return crypto.createHash('sha256').update((p&&p.userId)||'unknown').digest('hex').slice(0,40);}
function esc(v){return String(v||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');}
function d(v){return String(v||'').replace(/-/g,'');}
function dt(date,time){return d(date)+'T'+String(time||'00:00').replace(':','')+'00';}
function stamp(v){const x=new Date(v||Date.now());return x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');}
module.exports=async function(context,req){try{const p=principal(req);if(!p){context.res={status:401,body:'Ikke innlogget.'};return;}const year=Math.max(2000,Math.min(2100,Number((req.query&&req.query.year)||new Date().getFullYear())));const c=storage();await c.createTable().catch(()=>{});const pk=partitionFor(p),rows=[];for await(const e of c.listEntities({queryOptions:{filter:`PartitionKey eq '${pk}'`}})){const base=String(e.date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(base))continue;const eventDate=e.annual?`${year}${base.slice(4)}`:base;if(Number(eventDate.slice(0,4))!==year)continue;rows.push({...e,eventDate});}const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//IANS//Sameie Aarshjul//NO','CALSCALE:GREGORIAN','METHOD:PUBLISH','X-WR-CALNAME:IANS Årshjul '+year,'X-WR-TIMEZONE:Europe/Oslo'];for(const e of rows){lines.push('BEGIN:VEVENT',`UID:${e.rowKey}@ians.no`,`DTSTAMP:${stamp(e.updatedAt||e.createdAt)}`);if(e.allDay!==false||!e.startTime){lines.push(`DTSTART;VALUE=DATE:${d(e.eventDate)}`);const end=new Date(e.eventDate+'T12:00:00');end.setDate(end.getDate()+1);lines.push(`DTEND;VALUE=DATE:${String(end.getFullYear())+String(end.getMonth()+1).padStart(2,'0')+String(end.getDate()).padStart(2,'0')}`);}else{lines.push(`DTSTART;TZID=Europe/Oslo:${dt(e.eventDate,e.startTime)}`);if(e.endTime)lines.push(`DTEND;TZID=Europe/Oslo:${dt(e.eventDate,e.endTime)}`);}lines.push(`SUMMARY:${esc(e.title)}`,`CATEGORIES:${esc(e.category||'Oppgave')}`);if(e.notes)lines.push(`DESCRIPTION:${esc(e.notes)}`);if(e.annual)lines.push('RRULE:FREQ=YEARLY');if(e.systemNotify!==false&&Number(e.notifyDays||0)>0){lines.push('BEGIN:VALARM',`TRIGGER:-P${Number(e.notifyDays)}D`,'ACTION:DISPLAY',`DESCRIPTION:${esc('Påminnelse: '+e.title)}`,'END:VALARM');}lines.push('END:VEVENT');}lines.push('END:VCALENDAR');context.res={status:200,headers:{'Content-Type':'text/calendar; charset=utf-8','Content-Disposition':`attachment; filename="IANS-aarshjul-${year}.ics"`,'Cache-Control':'no-store'},body:lines.join('\r\n')};}catch(e){context.log.error(e);context.res={status:500,body:'Kunne ikke lage kalenderfil.'};}};