const { TableClient } = require('@azure/data-tables');
const { EmailClient } = require('@azure/communication-email');
const TABLE='IansYearWheel';
const BOARD_POLICY='Styremedlemmer har møteplikt. Dersom noe kommer i veien, meldes avbud i forkant. Varamedlemmer har ingen møteplikt, men kan møte om ønskelig. Styret trenger minst 3 deltakere for å gjennomføre møtet. Dersom ordinære styremedlemmer ikke kan møte, kan varamedlemmer bli kalt inn.';
const BOARD_RECIPIENTS=['straumsfjellet@styrerommet.no','henrik.bergfjord@outlook.com'];
const BOARD_MEETINGS=['2026-09-24','2026-10-29','2026-11-26','2026-12-30','2027-01-28','2027-02-25','2027-03-25'];
function json(status,body){return{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'},body};}
function storage(){const cs=process.env.IANS_BOOKING_STORAGE||process.env.AzureWebJobsStorage;if(!cs)throw new Error('Storage is not configured');return TableClient.fromConnectionString(cs,TABLE);}
function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function pad(n){return String(n).padStart(2,'0')}
function localIso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function emails(v,email){let a=[];if(v)a=String(v).split(/[;,\n]+/);if(email)a.push(email);return [...new Set(a.map(x=>String(x||'').trim().toLowerCase()).filter(x=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)))].slice(0,25);}
async function send(mail,sender,to,subject,plain,html){if(!to.length)return false;const poller=await mail.beginSend({senderAddress:sender,content:{subject,plainText:plain,html},recipients:{to:to.map(address=>({address}))}});await poller.pollUntilDone();return true;}
module.exports=async function(context,req){try{const expected=process.env.YEARWHEEL_NOTIFY_KEY;const supplied=req.headers['x-ians-notify-key']||'';if(!expected||supplied!==expected)return context.res=json(403,{ok:false,error:'Forbidden'});const emailCs=process.env.COMMUNICATION_SERVICES_CONNECTION_STRING;const sender=process.env.ACADEMY_EMAIL_SENDER||process.env.IANS_EMAIL_SENDER;if(!emailCs||!sender)return context.res=json(503,{ok:false,error:'Email is not configured'});const c=storage();await c.createTable().catch(()=>{});const mail=new EmailClient(emailCs);const now=new Date();const today=localIso(now);const year=now.getFullYear();let checked=0,sent=0;
for await(const e of c.listEntities()){checked++;if(e.systemNotify===false)continue;const days=Math.max(0,Number(e.notifyDays||0));const to=emails(e.recipients,e.email);if(!days||!to.length)continue;const base=String(e.date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(base))continue;const target=e.annual?`${year}${base.slice(4)}`:base;const td=new Date(target+'T12:00:00');if(Number.isNaN(td.getTime()))continue;const due=new Date(td);due.setDate(due.getDate()-days);if(localIso(due)!==today)continue;const notifyKey=`${target}:${days}`;if(e.lastNotifiedKey===notifyKey)continue;const subject=`Påminnelse: ${e.title} om ${days} ${days===1?'dag':'dager'}`;const plain=[subject,'',`Dato: ${target}`,e.startTime?`Tid: ${e.startTime}${e.endTime?'–'+e.endTime:''}`:'',`Kategori: ${e.category||'Oppgave'}`,e.notes?`Notat: ${e.notes}`:'','',`IANS Årshjul`].filter(Boolean).join('\n');const html=`<div style="font-family:Arial,sans-serif;max-width:680px"><h2>${esc(subject)}</h2><p><strong>Dato:</strong> ${esc(target)}${e.startTime?`<br><strong>Tid:</strong> ${esc(e.startTime)}${e.endTime?'–'+esc(e.endTime):''}`:''}<br><strong>Kategori:</strong> ${esc(e.category||'Oppgave')}</p>${e.notes?`<p>${esc(e.notes)}</p>`:''}<hr><p style="color:#777;font-size:12px">Automatisk varsel fra IANS Årshjul.</p></div>`;if(await send(mail,sender,to,subject,plain,html)){e.lastNotifiedKey=notifyKey;e.lastNotifiedAt=new Date().toISOString();await c.updateEntity(e,'Merge');sent++;}}
for(const target of BOARD_MEETINGS){const td=new Date(target+'T12:00:00');const due=new Date(td);due.setDate(due.getDate()-2);if(localIso(due)!==today)continue;const markerPk='SYSTEM';const markerRk='board-reminder-'+target;let already=false;try{await c.getEntity(markerPk,markerRk);already=true}catch{}if(already)continue;const subject=`Styremøte ${target} kl. 17:00 – påminnelse`;const plain=[subject,'',BOARD_POLICY,'','Avbud meldes i forkant slik at varamedlem kan kalles inn ved behov.','', 'IANS Årshjul · Straumsfjellet Panorama Sameie'].join('\n');const html=`<div style="font-family:Arial,sans-serif;max-width:680px"><h2>${esc(subject)}</h2><p>${esc(BOARD_POLICY)}</p><p><strong>Avbud meldes i forkant</strong> slik at varamedlem kan kalles inn ved behov.</p><hr><p style="color:#777;font-size:12px">Automatisk varsel fra IANS Årshjul · Straumsfjellet Panorama Sameie.</p></div>`;if(await send(mail,sender,BOARD_RECIPIENTS,subject,plain,html)){await c.createEntity({partitionKey:markerPk,rowKey:markerRk,sentAt:new Date().toISOString(),type:'board-reminder'});sent++;}}
context.res=json(200,{ok:true,checked,sent,date:today});}catch(e){context.log.error(e);context.res=json(500,{ok:false,error:'Reminder job failed'});}};