const KEY='iansRobloxAcademyV1';
const chapters=[
['🎮','Roblox-historien','Hvordan Roblox startet, hvem som bygget plattformen og hvordan den utviklet seg.'],
['🌍','Hva Roblox egentlig er','Forskjellen på Roblox, et spill, en experience, en server og en skaper.'],
['⚙️','Bak kulissene','Konto, avatar, servere, internett, lag og hvordan mange spiller sammen.'],
['💰','Robux og business','Robux, kjøp, utviklere, DevEx og hvorfor Roblox tjener penger når du bruker plattformen.'],
['🧠','Spillpsykologi','Belønninger, streaks, sjeldne ting, FOMO og hvorfor det kan være vanskelig å stoppe.'],
['👤','Hvem er bak avataren?','Hvorfor avatar, alder og brukernavn ikke beviser hvem et menneske egentlig er.'],
['💬','Chat og kommunikasjon','Hva du kan dele, hva du aldri bør dele og når en samtale må stoppes.'],
['🚨','Scam Academy','Gratis Robux, phishing, falske giveaways, lenker, QR-koder og falske administratorer.'],
['🤝','Sosiale situasjoner','Press, mobbing, utestenging, hemmeligheter, blokkering og rapportering.'],
['🔐','Beskytt kontoen','Passord, tofaktor, innlogging, recovery og kontoovertakelse.'],
['🛡️','Roblox Safety','Aldersgrupper, chatfiltre, foreldrekontroll, innholdsgrenser og sikkerhetsverktøy.'],
['🏆','Roblox Master','Store scenarioer som tester om du kan bruke kunnskapen selv.']
];
const Q=(ch,t,x,q,a,c,why,type='normal')=>({ch,t,x,q,a,c,why,type});
const lessons=[
Q(0,'Hvor begynte Roblox?','Roblox ble utviklet av David Baszucki og Erik Cassel. Arbeidet startet i 2004, og plattformen ble lansert offentlig i 2006. Ideen var at mennesker skulle kunne bygge og oppleve virtuelle verdener sammen.','Hva var en viktig idé bak Roblox?',['Bare ett ferdig spill','En plattform der brukere kan skape og spille mange opplevelser','En nettbutikk for spillkonsoller'],1,'Roblox er en plattform for brukerskapte opplevelser.'),
Q(0,'Fra DynaBlocks til Roblox','Tidlige versjoner brukte navnet DynaBlocks før navnet Roblox ble valgt. Navnet passer ideen om roboter og byggeklosser.','Var Roblox alltid navnet?',['Nei, et tidlig navn var DynaBlocks','Ja','Det het Robux'],0,'DynaBlocks var et tidlig navn.'),
Q(0,'Hvorfor vokste Roblox?','Roblox lot skapere bygge nye experiences. Dermed kunne innholdet vokse uten at ett studio måtte lage alt selv.','Hvem lager mye av innholdet?',['Bare Roblox-ansatte','Spillere og skapere på plattformen','Bare skoler'],1,'Skaperøkonomien er en viktig del av Roblox.'),
Q(0,'Roblox i dag','Roblox brukes av svært mange mennesker i mange land. Tallene endrer seg over tid, så gode digitale detektiver sjekker dato og kilde når de ser et brukertall.','Hva bør du gjøre når noen sier «Roblox har X millioner brukere»?',['Tro tallet for alltid','Sjekke kilde og dato','Gjette'],1,'Brukertall endrer seg og må dateres.'),
Q(1,'Roblox er ikke ett spill','Roblox er en plattform med mange experiences laget av forskjellige skapere. To Roblox-opplevelser kan derfor være helt forskjellige.','Hva er mest riktig?',['Roblox er bare ett spill','Roblox er en plattform med mange opplevelser','Alle Roblox-spill er laget av samme person'],1,'Plattform og enkeltspill er ikke det samme.'),
Q(1,'Hva er en experience?','En experience er en verden eller aktivitet du kan gå inn i på Roblox. Den kan være konkurranse, bygging, rollespill eller noe helt annet.','Kan forskjellige experiences ha forskjellige regler?',['Ja','Nei','Bare på søndager'],0,'Skaperne kan bygge svært ulike opplevelser.'),
Q(1,'Hvem er en creator?','Creators kan bygge experiences, modeller, klær og annet innhold. Roblox Studio er et viktig verktøy for å lage opplevelser.','Hva brukes Roblox Studio til?',['Å bygge Roblox-opplevelser','Å kjøpe ekte hus','Å reparere Wi-Fi'],0,'Studio er Roblox sitt skaperverktøy.'),
Q(1,'Popularitet betyr ikke automatisk trygt','Mange spillere kan være et tegn på at noe er populært, men popularitet beviser ikke at alt innhold eller alle mennesker der er trygge.','Et spill har enormt mange spillere. Betyr det at alt der er trygt?',['Ja','Nei','Bare hvis avataren er kul'],1,'Popularitet og sikkerhet er to forskjellige ting.','scenario'),
Q(2,'Serveren','Når du går inn i en multiplayer-opplevelse, kobles enheten din til systemer som holder styr på verden og spillerne.','Hva gjør en server blant annet?',['Hjelper mange spillere å dele samme digitale verden','Lader mobilen','Bestemmer skoleferien'],0,'Servere er en viktig del av flerspilleropplevelser.'),
Q(2,'Lag er ikke alltid dårlig Wi-Fi','Forsinkelse kan oppstå flere steder: enheten, Wi-Fi, internettforbindelsen, avstanden eller serveren.','Hvis Roblox lagger, er ruteren alltid skyldig?',['Ja','Nei','Alltid Roblox'],1,'En nettforbindelse består av mange deler.'),
Q(2,'Avatar og konto','Avataren er hvordan en spiller vises. Kontoen inneholder identitet på plattformen, innstillinger og digitale eiendeler.','Beviser en avatar hvem personen er i virkeligheten?',['Ja','Nei'],1,'En avatar er en digital figur, ikke legitimasjon.'),
Q(2,'Brukernavn er ikke identitet','Et navn som «Ian2017» eller «GirlAge9» kan velges av en bruker og er ikke bevis på alder, kjønn, skole eller bosted.','En spiller heter Boy9Norway. Vet du derfor at han er en norsk 9-åring?',['Ja','Nei'],1,'Brukernavn kan være oppdiktet.','scenario'),
Q(3,'Hva er Robux?','Robux er Roblox sin virtuelle valuta. Den kan brukes på digitale ting og funksjoner. Fordi Robux kjøpes med ekte penger, har valgene dine en virkelig kostnad.','Er Robux det samme som lekepenger uten verdi?',['Ja','Nei'],1,'Robux kan representere ekte pengebruk.'),
Q(3,'Hvordan tjener Roblox penger?','Roblox har en økonomi rundt blant annet kjøp av Robux og andre plattformtjenester. En del går videre i skaperøkonomien, mens Roblox også tjener på aktiviteten.','Hvor kommer pengene til Robux opprinnelig fra når familien kjøper dem?',['Ekte penger','Gratis strøm','XP'],0,'Virtuell valuta kan skjule hvor virkelig kostnaden er.'),
Q(3,'Creators kan tjene penger','Kvalifiserte skapere kan tjene Robux på innhold og i noen tilfeller veksle opptjente Robux gjennom Developer Exchange, DevEx.','Hvorfor ønsker noen skapere mange spillere?',['Flere spillere kan gi større mulighet for inntekt','Fordi serveren blir lettere','De får gratis skole'],0,'Oppmerksomheten din kan ha økonomisk verdi.'),
Q(3,'Pris i Robux','En ting koster 800 Robux. Det er lettere å trykke «kjøp» når prisen ikke står i kroner.','Hva bør du tenke før et Robux-kjøp?',['Robux er gratis','Hva dette faktisk koster og om kjøpet er verdt det','Kjøpe fort før en voksen ser det'],1,'Oversett virtuell valuta til et virkelig valg.','adult'),
Q(4,'Bare én runde til','Spill bruker mål, progresjon og belønninger fordi det gjør dem morsomme og kan holde oppmerksomheten din. Det betyr ikke at spillet bestemmer når du skal stoppe.','Hvem bør bestemme når du er ferdig?',['Spillet','Du og familiens regler','En tilfeldig spiller'],1,'Å forstå design gjør det lettere å styre egen tid.'),
Q(4,'FOMO','FOMO betyr frykten for å gå glipp av noe. Tidsbegrensede ting kan få deg til å føle at du må handle eller spille nå.','«Bare tilgjengelig i 10 minutter!» prøver ofte å skape hva?',['FOMO og hastverk','Bedre Wi-Fi','Sterkere passord'],0,'Hastverk gjør det vanskeligere å tenke rolig.'),
Q(4,'Sjeldne ting','Et digitalt objekt kan føles verdifullt fordi det er sjeldent, populært eller vanskelig å få. Følelsen betyr ikke at du må kjøpe det.','Hva er smartest når du føler «jeg MÅ ha den nå»?',['Kjøpe øyeblikkelig','Stoppe og tenke før du bruker penger','Låne passordet til en venn'],1,'En pause bryter presset.','scenario'),
Q(4,'Voksenoppdrag: kjøp og tid','Snakk sammen om familiens regler for Robux, kjøp og spilletid. Du skal kunne forklare hvorfor reglene finnes – ikke bare gjenta dem.','Hva er målet med regler?',['At voksne skal ødelegge spill','Å hjelpe oss å styre tid, penger og valg','At Roblox skal tjene mer'],1,'Gode regler gjør valgene tydelige før presset oppstår.','adult'),
Q(5,'Avataren kan lure hjernen','Vi mennesker bruker navn, klær og måten noen skriver på for å gjette hvem de er. På nettet kan alt dette konstrueres.','En avatar ser ut som et barn. Hva vet du sikkert?',['At personen er et barn','Ingenting sikkert om personens virkelige alder','At personen går på din skole'],1,'Utseendet på en avatar beviser ikke identitet.'),
Q(5,'Lang tid gjør ikke identiteten sikker','En person kan være hyggelig i uker eller måneder. Tid og vennlighet alene beviser fortsatt ikke hvem personen er.','En nettvenn har vært hyggelig i tre måneder. Kan du derfor dele adressen din?',['Ja','Nei'],1,'Tillit på nett må ha grenser.','scenario'),
Q(5,'Små spørsmål kan avsløre mye','Skole, fotballklubb, fullt navn, telefonnummer og hvor du bor kan kombineres til mye informasjon om deg.','Hva er personopplysninger?',['Opplysninger som kan fortelle hvem du er eller hvor du finnes','Bare passord','Bare bilder'],0,'Mange små opplysninger kan bli et stort puslespill.'),
Q(5,'Voksenoppdrag: hvem er personen?','Hent en voksen. Forklar hvorfor «Jeg er også 9» ikke er bevis. Den voksne skal deretter spørre deg om tre forskjellige måter en fremmed kan prøve å virke troverdig på.','Hva er den viktigste regelen?',['Avatar og ord er bevis på identitet','Jeg deler private ting når noen virker hyggelig','Jeg trenger ikke bevise noe for fremmede og henter en voksen ved private spørsmål'],2,'Du har alltid lov til å stoppe en samtale.','adult'),
Q(6,'Hva kan være privat?','Fullt navn, adresse, skole, telefonnummer, passord, bilder som avslører hvor du er og familiens opplysninger kan være private.','En spiller spør hvilken skole du går på. Hva gjør du?',['Forteller det','Lar være å dele og henter voksen hvis personen presser','Gir bare gatenavnet'],1,'Skole kan bidra til å finne deg.','scenario'),
Q(6,'Flytt samtalen hit','En spiller ber deg gå til en annen chat-app. Å flytte samtalen kan fjerne noen av Roblox sine sikkerhetsfiltre.','Hva bør du gjøre?',['Flytte samtalen i hemmelighet','Stoppe og spørre en voksen','Sende telefonnummer først'],1,'Ikke la en fremmed flytte samtalen bort fra sikkerhetsrammene.','scenario'),
Q(6,'Hemmeligheten','En spiller sier: «Ikke fortell foreldrene dine at vi snakker.»','Hva er riktig reaksjon?',['Holde hemmeligheten','Fortelle en trygg voksen','Slette alt og aldri si noe'],1,'Når noen krever hemmelighold fra voksne, skal varsellampen på.','scenario'),
Q(6,'Du får alltid lov å gå','Du skylder ingen på nettet et svar. Du kan forlate spillet, blokkere og hente hjelp selv om du tidligere har sagt ja til å chatte.','Må du være høflig og fortsette hvis du blir ukomfortabel?',['Ja','Nei'],1,'Din sikkerhet er viktigere enn å tilfredsstille en fremmed.'),
Q(7,'Gratis Robux','Løfter om gratis Robux brukes ofte for å lokke spillere til falske sider, undersøkelser eller innlogging.','En lenke lover 10 000 gratis Robux hvis du logger inn. Hva gjør du?',['Logger inn','Klikker ikke og sier fra til voksen','Tester med passordet først'],1,'Gratis-premien kan være agnet.','scenario'),
Q(7,'Phishing','Phishing er når noen lager en melding eller side som prøver å lure deg til å gi fra deg innlogging eller annen informasjon.','Hva er målet med phishing?',['Å hjelpe deg å huske passord','Å lure til seg informasjon eller tilgang','Å gjøre grafikken penere'],1,'Phishing etterligner ofte noe du stoler på.'),
Q(7,'Falsk administrator','En person skriver «ROBLOX ADMIN» og ber om passordet for å fikse kontoen.','Hva gjør du?',['Sender passord','Sender bare halvparten','Sender aldri passord og rapporterer ved behov'],2,'Legitime hjelpere trenger ikke passordet ditt.','scenario'),
Q(7,'QR-koder og korte lenker','En QR-kode er bare en måte å åpne informasjon eller en lenke på. Den blir ikke trygg fordi den er en QR-kode.','Bør du skanne en ukjent QR-kode for gratis Robux?',['Ja','Nei'],1,'Du må vurdere målet bak lenken, ikke bare formen.'),
Q(7,'Voksenoppdrag: scam-detektiv','Hent en voksen. Finn sammen på tre tegn som kan avsløre en svindel: utrolig premie, hastverk, hemmelighold, ukjent lenke eller spørsmål om innlogging.','Hva gjør du når to varsellamper dukker opp?',['Fortsetter raskt','Stopper, klikker ikke og spør en voksen','Sender lenken til venner'],1,'Stopp før du klikker.','adult'),
Q(8,'Mobbing er ikke bare «spill»','Ord og handlinger i digitale rom kan påvirke ekte mennesker. Gjentatt plaging, trusler eller utestenging skal tas alvorlig.','Hva kan du gjøre hvis noen plager deg?',['Blokkere/rapportere og snakke med voksen','Gi dem passordet','Mobbe tilbake'],0,'Du trenger ikke løse mobbing alene.'),
Q(8,'Press fra venner','Også ekte venner kan presse deg til kjøp eller ting du ikke ønsker.','En venn sier «kjøp denne ellers får du ikke være med». Hva er smartest?',['Kjøpe','Si nei og snakke med voksen hvis presset fortsetter','Gi vennen kontoen'],1,'Vennskap skal ikke kreve kjøp.','scenario'),
Q(8,'Rapportering er et verktøy','Rapportering kan hjelpe plattformen å undersøke brudd på reglene. Blokkering kan stoppe direkte kontakt.','Er blokkering det samme som å være slem?',['Ja','Nei, det kan være en sikkerhetsgrense'],1,'Grenser er lov.'),
Q(8,'Når må en voksen inn?','Trusler, seksuelle spørsmål, forespørsler om bilder, penger, møte i virkeligheten, hemmelighold eller gjentatt press er situasjoner der du ikke skal stå alene.','Hva gjør du ved en alvorlig eller rar henvendelse?',['Skjuler den','Henter en trygg voksen','Forhandler'],1,'Voksne kan hjelpe med vurdering, dokumentasjon og rapportering.','adult'),
Q(9,'Passordet er nøkkelen','Et godt passord skal ikke deles med venner. Bruk et unikt passord som ikke brukes på andre tjenester.','Beste regel?',['Samme passord overalt','Unikt passord og aldri dele det','Navnet ditt som passord'],1,'Ett lekket passord skal ikke åpne flere kontoer.'),
Q(9,'Tofaktor','Tofaktorinnlogging legger til en ekstra kontroll ved innlogging. Det kan gjøre et stjålet passord mindre nyttig for angriperen.','Hvorfor bruke tofaktor?',['Ekstra beskyttelse','Mer Robux','Raskere server'],0,'Flere bevis på at du er deg gjør overtakelse vanskeligere.'),
Q(9,'Innlogget på fremmed maskin','En delt eller fremmed enhet kan lagre økten eller passordet ditt.','Hva er tryggest?',['Unngå innlogging på ukjente enheter og logge ut etter bruk','La kontoen stå åpen','Dele innlogging'],0,'Kontotilgang skal behandles som en nøkkel.','scenario'),
Q(9,'Hvis noe allerede gikk galt','Hvis du tror noen har fått tilgang, er det viktig å si fra raskt, endre legitimasjon via riktige kanaler og sikre kontoen.','Bør du skjule en feil fordi du er redd for å få kjeft?',['Ja','Nei, hent hjelp raskt'],1,'Tidlig hjelp kan begrense skaden.','adult'),
Q(10,'Alder betyr noe','Roblox bruker aldersgrupper og alderskontroller for å tilpasse innhold og kommunikasjon. Funksjoner og regler kan endres over tid og variere etter region.','Hvorfor skal fødselsdato/alder være riktig?',['For at aldersbaserte sikkerhetsvalg skal passe bedre','For flere gratis Robux','Det spiller ingen rolle'],0,'Riktig alder er en del av sikkerhetsmodellen.'),
Q(10,'9–12 år','For alderskontrollerte brukere i 9–12-gruppen har Roblox egne begrensninger. Enkelte kommunikasjonsfunksjoner krever foreldretillatelse.','Betyr en sikkerhetsinnstilling at du kan slutte å tenke selv?',['Ja','Nei'],1,'Tekniske filtre hjelper, men erstatter ikke dømmekraft.'),
Q(10,'Foreldrekontroll','En koblet voksenkonto kan brukes til å styre blant annet innhold, kommunikasjon, skjermtid og pengebruk, avhengig av alder og gjeldende Roblox-regler.','Hvorfor finnes foreldrekontroll?',['For å hjelpe familien å sette passende grenser','For å vinne spill','For å lese alle tanker'],0,'Kontrollene er verktøy for familiegrenser.'),
Q(10,'Filtre er ikke magi','Roblox bruker moderering og filtre, men ingen teknisk løsning kan garantere at alle mennesker eller alt innhold alltid er trygt.','Hva er den beste kombinasjonen?',['Filtre + egen dømmekraft + voksenhjelp','Bare filtre','Ingen regler'],0,'Sikkerhet bygges i flere lag.'),
Q(10,'Voksenoppdrag: sjekk kontoen','Hent en voksen og åpne Roblox sine foreldrekontroller sammen. Se på alder, innhold, kommunikasjon, skjermtid og pengebruk. Ikke endre noe uten at dere er enige.','Hva skal du kunne forklare etterpå?',['Hvorfor familiens viktigste innstillinger finnes','Bare hvor menyknappen er','Hvordan man slår av alt'],0,'Å forstå innstillingen er viktigere enn bare å ha den på.','adult'),
Q(11,'Master: den hyggelige fremmede','En spiller du har kjent digitalt lenge spør etter fotballklubben din «så vi kan se om vi bor nær hverandre».','Hva gjør du?',['Forteller klubben','Deler ikke og sier fra til voksen hvis personen fortsetter','Gir bare treningstid'],1,'Små opplysninger kan avsløre hvor du er.','scenario'),
Q(11,'Master: den fantastiske premien','Du får melding om en ekstremt sjelden item. Du må logge inn via en lenke innen fem minutter.','Hvilke varsellamper ser du?',['Premie + hastverk + ekstern innlogging','Ingen','Bare dårlig stavemåte'],0,'Flere manipulasjonstegn samtidig betyr stopp.','scenario'),
Q(11,'Master: ekte venn','En ekte klassekamerat ber om passordet fordi han skal «fikse avataren» din.','Er det greit fordi du kjenner ham?',['Ja','Nei'],1,'Passord deles ikke, heller ikke med venner.','scenario'),
Q(11,'Master: hemmelig chat','En nettvenn sier at foreldrene dine ikke forstår Roblox og at dere bør snakke privat et annet sted.','Hva er smartest?',['Følge etter','Stoppe og fortelle voksen','Holde det hemmelig'],1,'Forsøk på hemmelig isolert kontakt er et tydelig faresignal.','scenario'),
Q(11,'Master: kjøpspress','En tidsbegrenset pakke koster mye Robux og du kjenner panikk for å gå glipp av den.','Hva viser at du styrer spillet og ikke omvendt?',['Jeg kjøper før tiden går ut','Jeg tar pause og vurderer med en voksen hvis det koster penger','Jeg låner Robux'],1,'Evnen til å stoppe er en superkraft.','scenario'),
Q(11,'Master: du gjorde en feil','Du klikket allerede på en rar lenke og skrev inn passordet.','Hva gjør du nå?',['Skjuler det','Henter voksen med en gang og sikrer kontoen','Venter en uke'],1,'Feil skal utløse hjelp, ikke hemmelighold.','adult')
];
let state={done:[],wrong:0,adult:[]},current=null;
try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
state.done=[...new Set((state.done||[]).filter(Number.isInteger))];state.adult=[...new Set((state.adult||[]).filter(Number.isInteger))];
const $=id=>document.getElementById(id);const chapterIndices=c=>lessons.map((l,i)=>l.ch===c?i:-1).filter(i=>i>=0);const chapterDone=c=>chapterIndices(c).filter(i=>state.done.includes(i)).length;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function unlocked(c){return c===0||chapterDone(c-1)===chapterIndices(c-1).length}
function render(){const pct=Math.round(100*state.done.length/lessons.length);$('progressText').textContent=`${state.done.length}/${lessons.length} oppdrag fullført`;$('scoreText').textContent=`${pct}% gjennomført`;$('adultText').textContent=`${state.adult.length} voksenoppdrag`;$('bar').style.width=pct+'%';$('chapterGrid').innerHTML=chapters.map((c,i)=>{const d=chapterDone(i),n=chapterIndices(i).length,l=!unlocked(i);return `<button class="card chapter ${l?'locked':''}" ${l?'disabled':''} onclick="openChapter(${i})"><div style="font-size:34px">${c[0]}</div><h3>${i+1}. ${c[1]}</h3><p class="muted">${c[2]}</p><b>${d}/${n}</b><div class="progress"><span style="width:${100*d/n}%"></span></div></button>`}).join('')}
function openChapter(c){if(!unlocked(c))return;const idx=chapterIndices(c).find(i=>!state.done.includes(i))??chapterIndices(c)[0];openLesson(idx)}
function openLesson(i){current=i;if(window.IANSRobloxFocus)window.IANSRobloxFocus.enter();const l=lessons[i],done=state.done.includes(i);$('lesson').hidden=false;$('lesson').className='card '+(l.type==='adult'?'adult':l.type==='scenario'?'scenario':'');$('lesson').innerHTML=`<div><b>${chapters[l.ch][0]} KAPITTEL ${l.ch+1} · OPPDRAG ${chapterIndices(l.ch).indexOf(i)+1}/${chapterIndices(l.ch).length}</b>${l.type==='adult'?'<b> · 👨‍👦 VOKSENOPPDRAG</b>':l.type==='scenario'?'<b> · 🧭 SCENARIO</b>':''}</div><h2>${l.t}</h2><p class="muted" style="line-height:1.65">${l.x}</p><h3>${l.q}</h3><div class="answers">${l.a.map((a,j)=>`<button class="answer" ${done?'disabled':''} onclick="answer(${j})">${a}</button>`).join('')}</div><div id="feedback" style="margin-top:14px">${done?'✅ '+l.why:''}</div><div class="actions"><button class="btn" onclick="document.getElementById('chapters').scrollIntoView()">Alle kapitler</button>${done?'<button class="btn" onclick="nextLesson()">Neste →</button>':''}</div>`;$('lesson').scrollIntoView({behavior:'smooth',block:'start'})}
function answer(j){if(current===null||state.done.includes(current))return;const l=lessons[current],f=$('feedback');if(j===l.c){state.done.push(current);if(l.type==='adult')state.adult.push(current);save();render();openLesson(current);if(window.IANSRobloxFocus)window.IANSRobloxFocus.refresh();f.className='good'}else{state.wrong++;save();f.className='bad';f.textContent='Ikke helt. Tenk på hvorfor noen ønsker at du skal velge dette, og prøv igjen.'}}
function nextLesson(){const l=lessons[current],arr=chapterIndices(l.ch),pos=arr.indexOf(current);if(pos<arr.length-1)return openLesson(arr[pos+1]);render();if(l.ch<chapters.length-1&&unlocked(l.ch+1))openChapter(l.ch+1)}
render();