const KEY='iansRobloxAcademyV1';
const chapters=[
['🎮','Roblox-historien','Hvordan Roblox startet, hvem som bygget plattformen og hvordan den utviklet seg.'],
['🌍','Hva Roblox egentlig er','Forskjellen på Roblox, et spill, en experience, en server og en skaper.'],
['⚙️','Bak kulissene','Konto, avatar, servere, internett, lag og hvordan mange spiller sammen.'],
['💰','Robux og business','Robux, kjøp, utviklere, DevEx og hvorfor Roblox tjener penger når du bruker plattformen.'],
['🧠','Spillpsykologi','Belønninger, streaks, sjeldne ting, FOMO og hvorfor det kan være vanskelig å stoppe.'],
['👤','Hvem er bak avataren?','Hvorfor avatar, alder og brukernavn ikke beviser hvem et menneske egentlig er.'],
['💬','Chat og kommunikasjon','Hva du kan dele, hva du aldri bør dele og når en samtale må stoppes.'],
['🚨','Scam Academy','Gratis Robux, phishing, falske giveaways, lenker, QR-koder og falske administratorer.'],
['🤝','Sosiale situasjoner','Press, mobbing, utestenging, hemmeligheter, blokkering og rapportering.'],
['🔐','Beskytt kontoen','Passord, tofaktor, innlogging, recovery og kontoovertakelse.'],
['🛡️','Roblox Safety','Aldersgrupper, chatfiltre, foreldrekontroll, innholdsgrenser og sikkerhetsverktøy.'],
['🏆','Roblox Master','Store scenarioer som tester om du kan bruke kunnskapen selv.']
];
const Q=(ch,t,x,q,a,c,why,type='normal')=>({ch,t,x,q,a,c,why,type});
const lessons=[
Q(0,'Hvor begynte Roblox?','Roblox ble utviklet av David Baszucki og Erik Cassel. Arbeidet startet i 2004, og plattformen ble lansert offentlig i 2006. Ideen var at mennesker skulle kunne bygge og oppleve virtuelle verdener sammen.','Hva var en viktig idé bak Roblox?',['Bare ett ferdig spill','En plattform der brukere kan skape og spille mange opplevelser','En nettbutikk for spillkonsoller'],1,'Roblox er en plattform for brukerskapte opplevelser.'),
Q(0,'Fra DynaBlocks til Roblox','Tidlige versjoner brukte navnet DynaBlocks før navnet Roblox ble valgt. Navnet passer ideen om roboter og byggeklosser.','Var Roblox alltid navnet?',['Nei, et tidlig navn var DynaBlocks','Ja','Det het Robux'],0,'DynaBlocks var et tidlig navn.'),
Q(0,'Hvorfor vokste Roblox?','Roblox lot skapere bygge nye experiences. Dermed kunne innholdet vokse uten at ett studio måtte lage alt selv.','Hvem lager mye av innholdet?',['Bare Roblox-ansatte','Spillere og skapere på plattformen','Bare skoler'],1,'Skaperøkonomien er en viktig del av Roblox.'),
Q(0,'Roblox i dag','Roblox brukes av svært mange mennesker i mange land. Tallene endrer seg over tid, så gode digitale detektiver sjekker dato og kilde når de ser et brukertall.','Hva bør du gjøre når noen sier «Roblox har X millioner brukere»?',['Tro tallet for alltid','Sjekke kilde og dato','Gjette'],1,'Brukertall endrer seg og må dateres.'),
Q(1,'Roblox er ikke ett spill','Roblox er en plattform med mange experiences laget av forskjellige skapere. To Roblox-opplevelser kan derfor være helt forskjellige.','Hva er mest riktig?',['Roblox er bare ett spill','Roblox er en plattform med mange opplevelser','Alle Roblox-spill er laget av samme person'],1,'Plattform og enkeltspill er ikke det samme.'),
Q(1,'Hva er en experience?','En experience er en verden eller aktivitet du kan gå inn i på Roblox. Den kan være konkurranse, bygging, rollespill eller noe helt annet.','To experiences ser nesten like ut. Kan reglene og måten de fungerer på likevel være forskjellige?',['Ja, fordi skaperne kan bygge dem med ulike regler','Nei, alle Roblox-opplevelser følger nøyaktig samme spillregler','Bare hvis den ene krever Robux'],0,'Skaperne kan bygge svært ulike opplevelser.'),
Q(1,'Hvem er en creator?','Creators kan bygge experiences, modeller, klær og annet innhold. Roblox Studio er et viktig verktøy for å lage opplevelser.','Hva skiller Roblox Studio fra selve Roblox-appen du vanligvis spiller i?',['Studio brukes til å lage og programmere opplevelser, mens Roblox brukes til å spille dem','Studio er bare en annen måte å kjøpe Robux på','Studio brukes bare til å endre avataren din'],0,'Studio er Roblox sitt skaperverktøy.'),
Q(1,'Popularitet betyr ikke automatisk trygt','Mange spillere kan være et tegn på at noe er populært, men popularitet beviser ikke at alt innhold eller alle mennesker der er trygge.','Et spill har millioner av besøk og svært gode vurderinger. Hva kan du egentlig konkludere med?',['At spillet er populært, men ikke at alt innhold og alle spillere er trygge','At alle spillerne er kontrollert av Roblox','At spillet er trygt så lenge vennene mine også spiller det'],0,'Popularitet og sikkerhet er to forskjellige ting.','scenario'),
Q(2,'Serveren','Når du går inn i en multiplayer-opplevelse, kobles enheten din til systemer som holder styr på verden og spillerne.','Du og en venn ser hverandre bevege dere i samme Roblox-verden fra to forskjellige hus. Hva er serverens viktigste rolle her?',['Den holder den delte spillverdenen og spillernes handlinger synkronisert','Den gjør Wi-Fi-signalet sterkere hjemme hos begge','Den lagrer automatisk alle passordene til spillerne'],0,'Servere er en viktig del av flerspilleropplevelser.'),
Q(2,'Lag er ikke alltid dårlig Wi-Fi','Forsinkelse kan oppstå flere steder: enheten, Wi-Fi, internettforbindelsen, avstanden eller serveren.','Roblox hakker, men en annen enhet hjemme streamer video uten problemer. Hva er den beste konklusjonen?',['Ruteren må være ødelagt siden Roblox hakker','Feilen kan fortsatt ligge flere steder, for eksempel enheten, forbindelsen eller spillserveren','Roblox-serveren må være problemet fordi video fungerer'],1,'En nettforbindelse består av mange deler.'),
Q(2,'Avatar og konto','Avataren er hvordan en spiller vises. Kontoen inneholder identitet på plattformen, innstillinger og digitale eiendeler.','En avatar ser ut som en gutt på din alder og personen skriver om de samme spillene som deg. Hva vet du sikkert?',['At personen omtrent er på min alder','At personen sannsynligvis er et barn, så private opplysninger er greit','Jeg vet fortsatt ikke sikkert hvem eller hvor gammel personen er'],2,'En avatar er en digital figur, ikke legitimasjon.'),
Q(2,'Brukernavn er ikke identitet','Et navn som «Ian2017» eller «GirlAge9» kan velges av en bruker og er ikke bevis på alder, kjønn, skole eller bosted.','En spiller heter Boy9Norway, skriver norsk og sier han går i 4. klasse. Hva er smartest å tenke?',['Flere detaljer gjør det sikkert at han er ni år','Det høres troverdig ut, men opplysningene kan fortsatt være oppdiktet','Han er trygg hvis kontoen har eksistert lenge'],1,'Brukernavn kan være oppdiktet.','scenario'),
Q(3,'Hva er Robux?','Robux er Roblox sin virtuelle valuta. Den kan brukes på digitale ting og funksjoner. Fordi Robux kjøpes med ekte penger, har valgene dine en virkelig kostnad.','Du har allerede Robux på kontoen. Hvorfor bør du likevel tenke på dem som noe med virkelig verdi?',['Fordi Robux kan være kjøpt for ekte penger selv om betalingen skjedde tidligere','Fordi alle Robux senere kan veksles tilbake til kontanter av alle spillere','Fordi hvert Robux alltid er verdt én norsk krone'],0,'Robux kan representere ekte pengebruk.'),
Q(3,'Hvordan tjener Roblox penger?','Roblox har en økonomi rundt blant annet kjøp av Robux og andre plattformtjenester. En del går videre i skaperøkonomien, mens Roblox også tjener på aktiviteten.','Hvorfor kan en pris på 800 Robux føles lettere å godta enn samme kjøp vist direkte i kroner?',['Fordi virtuell valuta kan gjøre den virkelige kostnaden mindre tydelig','Fordi Robux ikke har noen forbindelse til ekte penger etter kjøpet','Fordi Roblox alltid gjør kjøpet billigere når prisen vises i Robux'],0,'Virtuell valuta kan skjule hvor virkelig kostnaden er.'),
Q(3,'Creators kan tjene penger','Kvalifiserte skapere kan tjene Robux på innhold og i noen tilfeller veksle opptjente Robux gjennom Developer Exchange, DevEx.','En creator designer en experience slik at spillerne kommer tilbake ofte og kanskje kjøper ting. Hvorfor kan det være verdifullt for skaperen?',['Mer aktivitet kan gi større muligheter for Robux og inntekt','Roblox betaler automatisk alle creators samme beløp per spiller','Mange spillere gjør at skaperen slipper å følge Roblox sine regler'],0,'Oppmerksomheten din kan ha økonomisk verdi.'),
Q(3,'Pris i Robux','En ting koster 800 Robux. Det er lettere å trykke «kjøp» når prisen ikke står i kroner.','Du har 1000 Robux og ser noe til 800. Hva viser best at du forstår kjøpet?',['Jeg har nok Robux, så prisen spiller ingen rolle','Jeg vurderer hva Robuxene kostet, hva jeg sitter igjen med og om tingen faktisk er verdt det','Jeg kjøper før jeg rekker å ombestemme meg'],1,'Et smart kjøp handler både om pris, verdi og konsekvens.','adult'),
Q(4,'Bare én runde til','Spill bruker mål, progresjon og belønninger fordi det gjør dem morsomme og kan holde oppmerksomheten din. Det betyr ikke at spillet bestemmer når du skal stoppe.','Du hadde avtalt å stoppe klokken 19, men mangler bare én seier til neste belønning. Hva viser mest kontroll?',['Jeg spiller til belønningen fordi jeg nesten er ferdig','Jeg følger avtalen og fortsetter en annen gang','Jeg fortsetter hvis spillet sier at belønningen er sjelden'],1,'Å kunne stoppe midt i et mål viser at du styrer spillet – ikke omvendt.'),
Q(4,'FOMO','FOMO betyr frykten for å gå glipp av noe. Tidsbegrensede ting kan få deg til å føle at du må handle eller spille nå.','En pakke forsvinner om ti minutter og nedtellingen blinker på skjermen. Hva er viktigst å forstå?',['Nedtellingen kan skape hastverk slik at jeg vurderer kjøpet mindre rolig','Alt med nedtelling er svindel','Jeg taper penger hvis jeg ikke kjøper'],0,'Hastverk kan påvirke beslutningen selv når tilbudet er ekte.'),
Q(4,'Sjeldne ting','Et digitalt objekt kan føles verdifullt fordi det er sjeldent, populært eller vanskelig å få. Følelsen betyr ikke at du må kjøpe det.','En venn har fått en sjelden item og plutselig ønsker du den mye mer enn før. Hva kan ha påvirket deg?',['Bare den tekniske kvaliteten på itemen','Sjeldenhet og sosial påvirkning kan gjøre den mer fristende','At kontoen min trenger den for å være sikker'],1,'Vi kan ønske noe sterkere når det virker sjeldent eller andre har det.','scenario'),
Q(4,'Voksenoppdrag: kjøp og tid','Snakk sammen om familiens regler for Robux, kjøp og spilletid. Du skal kunne forklare hvorfor reglene finnes – ikke bare gjenta dem.','Hvilken familieavtale fungerer best når et spennende tilbud dukker opp?',['En regel vi har bestemt på forhånd og forstår hvorfor finnes','En regel vi finner på etter at kjøpet er gjort','At spillet bestemmer fordi det kjenner tilbudet best'],0,'Regler bestemt på forhånd gjør det lettere å stå imot press i øyeblikket.','adult'),
Q(5,'Avataren kan lure hjernen','Vi mennesker bruker navn, klær og måten noen skriver på for å gjette hvem de er. På nettet kan alt dette konstrueres.','En spiller har barneavatar, bruker barnslige uttrykk og kjenner de samme YouTuberne som deg. Hva beviser dette?',['At personen nesten sikkert er et barn','At personen kjenner ting barn liker, men ikke hvem personen faktisk er','At det er trygt å fortelle hvilken skole jeg går på'],1,'Mange troverdige detaljer kan fortsatt konstrueres.'),
Q(5,'Lang tid gjør ikke identiteten sikker','En person kan være hyggelig i uker eller måneder. Tid og vennlighet alene beviser fortsatt ikke hvem personen er.','En nettvenn har aldri vært slem på seks måneder og spør nå hvor du trener fotball. Hva er den beste vurderingen?',['Lang kontakt gjør det trygt å dele','Jeg kan dele fordi fotball ikke er hemmelig','Jeg deler ikke stedsopplysninger bare fordi personen har vært hyggelig lenge'],2,'Tid bygger kjennskap, men beviser ikke identitet.','scenario'),
Q(5,'Små spørsmål kan avsløre mye','Skole, fotballklubb, fullt navn, telefonnummer og hvor du bor kan kombineres til mye informasjon om deg.','Du har aldri sagt adressen din, men har fortalt skole, klubb og fornavn. Hvorfor kan dette fortsatt være et problem?',['Opplysningene kan kombineres og gjøre det lettere å finne ut hvem eller hvor jeg er','Det er helt trygt så lenge adressen mangler','Bare passord kan brukes til å finne informasjon'],0,'Personvern handler også om hva flere små opplysninger avslører sammen.'),
Q(5,'Voksenoppdrag: hvem er personen?','Hent en voksen. Forklar hvorfor «Jeg er også 9» ikke er bevis. Den voksne skal deretter spørre deg om tre forskjellige måter en fremmed kan prøve å virke troverdig på.','En person gir deg mange detaljer som passer med historien sin. Hva er den beste regelen?',['Mange detaljer er det samme som identitetsbevis','Jeg kan være vennlig uten å dele private opplysninger eller stole på ubekreftet identitet','Jeg bør prøve å avsløre personen selv'],1,'Du trenger ikke vite hvem en fremmed er for å sette trygge grenser.','adult'),
Q(6,'Hva kan være privat?','Fullt navn, adresse, skole, telefonnummer, passord, bilder som avslører hvor du er og familiens opplysninger kan være private.','Du sender et bilde uten adresse eller skolenavn. I bakgrunnen står navnet på fotballklubben din. Hva bør du tenke på?',['Bildets bakgrunn kan også avsløre informasjon om hvor jeg holder til','Bilder er alltid trygge når ansiktet ikke vises','Klubbnavn regnes som passord'],0,'Informasjon kan ligge i bakgrunnen av et bilde, ikke bare i teksten.','scenario'),
Q(6,'Flytt samtalen hit','En spiller ber deg gå til en annen chat-app. Å flytte samtalen kan fjerne noen av Roblox sine sikkerhetsfiltre.','En hyggelig spiller sier at Roblox-chatten er dårlig og vil fortsette samtalen privat i en annen app. Hva er smartest?',['Flytte samtalen fordi begrunnelsen høres logisk ut','Stoppe og involvere en voksen før jeg flytter kontakt med noen jeg bare kjenner fra nettet','Gi telefonnummeret, men ikke adressen'],1,'En troverdig forklaring gjør ikke privat kontakt automatisk trygg.','scenario'),
Q(6,'Hemmeligheten','En spiller sier: «Ikke fortell foreldrene dine at vi snakker.»','Hvorfor er ønsket om hemmelighold et sterkere faresignal enn en vanlig privat samtale?',['Fordi personen prøver å holde en trygg voksen utenfor','Fordi alle hemmeligheter på nettet er ulovlige','Fordi Roblox automatisk sletter hemmelige meldinger'],0,'Forsøk på å isolere deg fra voksne er et viktig faresignal.','scenario'),
Q(6,'Du får alltid lov å gå','Du skylder ingen på nettet et svar. Du kan forlate spillet, blokkere og hente hjelp selv om du tidligere har sagt ja til å chatte.','Du har selv startet samtalen, men den begynner å føles ubehagelig. Hva gjelder nå?',['Jeg må fortsette fordi jeg startet den','Jeg kan stoppe når som helst, blokkere ved behov og hente hjelp','Jeg må forklare personen hvorfor før jeg kan gå'],1,'Et tidligere ja tar aldri bort retten din til å stoppe.'),
Q(7,'Gratis Robux','Løfter om gratis Robux brukes ofte for å lokke spillere til falske sider, undersøkelser eller innlogging.','En venn sender en lenke og sier at han selv fikk gratis Robux der. Hva er den beste vurderingen?',['Lenken er trygg fordi den kom fra en venn','Jeg bør fortsatt være skeptisk – vennen kan ta feil eller kontoen hans kan være misbrukt','Jeg kan teste siden så lenge jeg bare skriver brukernavnet først'],1,'Hvem som sender en lenke er ikke alene nok til å bevise at den er trygg.','scenario'),
Q(7,'Phishing','Phishing er når noen lager en melding eller side som prøver å lure deg til å gi fra deg innlogging eller annen informasjon.','En innloggingsside ser nesten helt lik ut som Roblox. Hva er viktigst å forstå?',['Et kjent utseende beviser at siden er ekte','Falske sider kan kopiere logo, farger og design, så jeg må vurdere hvor siden faktisk kommer fra','Siden er trygg hvis logoen har høy oppløsning'],1,'Phishing virker nettopp fordi falske sider kan se troverdige ut.'),
Q(7,'Falsk administrator','En person skriver «ROBLOX ADMIN» og ber om passordet for å fikse kontoen.','Personen kjenner brukernavnet ditt og beskriver et problem du faktisk har. Deretter ber han om passordet. Hva veier tyngst?',['At han kjenner problemet, så han må være ekte','At passordforespørselen er et alvorlig faresignal uansett hvor troverdig resten virker','At jeg kan sende passordet og endre det etterpå'],1,'Troverdige detaljer gjør aldri deling av passord riktig.','scenario'),
Q(7,'QR-koder og korte lenker','En QR-kode er bare en måte å åpne informasjon eller en lenke på. Den blir ikke trygg fordi den er en QR-kode.','Hvorfor kan en QR-kode eller kort lenke kreve ekstra oppmerksomhet?',['Fordi det kan være vanskeligere å se hvor den fører før jeg åpner den','Fordi alle QR-koder inneholder virus','Fordi Roblox forbyr alle korte lenker'],0,'Når målet er mindre synlig, bør du være ekstra forsiktig før du åpner.'),
Q(7,'Voksenoppdrag: scam-detektiv','Hent en voksen. Finn sammen på tre tegn som kan avsløre en svindel: utrolig premie, hastverk, hemmelighold, ukjent lenke eller spørsmål om innlogging.','En melding har riktig logo og godt språk, men lover en stor premie, krever rask handling og sender deg til en ukjent lenke. Hva bør avgjøre?',['Det profesjonelle utseendet','Kombinasjonen av flere faresignaler','At teksten ikke har stavefeil'],1,'Vurder handlingen meldingen prøver å få deg til å gjøre – ikke bare hvordan den ser ut.','adult'),
Q(8,'Mobbing er ikke bare «spill»','Ord og handlinger i digitale rom kan påvirke ekte mennesker. Gjentatt plaging, trusler eller utestenging skal tas alvorlig.','Noen sier at plagingen «bare er tull», men den fortsetter og du blir lei deg. Hva er viktigst?',['At de kaller det tull','Hvordan handlingene faktisk påvirker deg og at du kan hente hjelp','At du må bevise at de mente å være slemme'],1,'Gjentatt plaging kan være alvorlig selv om andre kaller det en spøk.'),
Q(8,'Press fra venner','Også ekte venner kan presse deg til kjøp eller ting du ikke ønsker.','Flere venner kjøper samme gamepass og sier du blir hengende etter uten det. Hva viser et selvstendig valg?',['Jeg kjøper fordi flertallet gjør det','Jeg vurderer selv behov, pris og familiens regler før jeg bestemmer meg','Jeg låner en annens konto for å teste'],1,'Gruppepress skal ikke ta over vurderingen din.','scenario'),
Q(8,'Rapportering er et verktøy','Rapportering kan hjelpe plattformen å undersøke brudd på reglene. Blokkering kan stoppe direkte kontakt.','Hva er forskjellen på blokkering og rapportering?',['Blokkering kan begrense kontakt, mens rapportering kan varsle plattformen om mulig regelbrudd','De er alltid nøyaktig det samme','Rapportering brukes bare når du har glemt passordet'],0,'Verktøyene kan ha forskjellige roller og kan brukes sammen.'),
Q(8,'Når må en voksen inn?','Trusler, seksuelle spørsmål, forespørsler om bilder, penger, møte i virkeligheten, hemmelighold eller gjentatt press er situasjoner der du ikke skal stå alene.','En fremmed spør først om vanlige spillting, men begynner senere å spørre hvor du bor og om dere kan møtes. Hva er riktig neste steg?',['Fortsette litt til for å finne ut hvem personen er','Stoppe kontakten og hente en trygg voksen','Gi et omtrentelig område, men ikke adressen'],1,'Når samtalen går mot sted eller fysisk møte, skal en trygg voksen inn.','adult'),
Q(9,'Passordet er nøkkelen','Et godt passord skal ikke deles med venner. Bruk et unikt passord som ikke brukes på andre tjenester.','Hvorfor er det ekstra viktig at Roblox-passordet ikke er det samme som passordet på andre tjenester?',['Hvis ett passord blir avslørt, kan noen ellers prøve det samme på flere kontoer','Roblox krever at hvert passord inneholder navnet på tjenesten','Samme passord gjør internettforbindelsen tregere'],0,'Unike passord begrenser hvor stor skade ett lekket passord kan gjøre.'),
Q(9,'Tofaktor','Tofaktorinnlogging legger til en ekstra kontroll ved innlogging. Det kan gjøre et stjålet passord mindre nyttig for angriperen.','Noen har fått tak i passordet ditt, men kontoen har tofaktor. Hva er den beste forklaringen?',['Kontoen er garantert umulig å overta','Tofaktor kan gi et ekstra hinder, men passordet må fortsatt behandles som kompromittert','Jeg trenger aldri å endre passord når tofaktor er på'],1,'Tofaktor er et ekstra sikkerhetslag, ikke en grunn til å ignorere et lekket passord.'),
Q(9,'Innlogget på fremmed maskin','En delt eller fremmed enhet kan lagre økten eller passordet ditt.','Du logger ut av Roblox på en delt PC. Hvorfor bør du fortsatt være forsiktig med å bruke fremmede enheter?',['Nettleseren eller enheten kan ha lagret informasjon, og jeg har mindre kontroll over hvordan den er sikret','Utlogging ødelegger alltid PC-en','Roblox tillater bare én enhet per konto'],0,'På en enhet du ikke kontrollerer, vet du mindre om lagring og sikkerhet.','scenario'),
Q(9,'Hvis noe allerede gikk galt','Hvis du tror noen har fått tilgang, er det viktig å si fra raskt, endre legitimasjon via riktige kanaler og sikre kontoen.','Du oppdager en innlogging du ikke kjenner igjen. Hva er den beste rekkefølgen?',['Ignorere den og se om det skjer igjen','Hente voksen, sikre kontoen via riktige kanaler og kontrollere sikkerhetsinnstillingene','Skrive til tilfeldige spillere og spørre hvem som logget inn'],1,'Rask sikring og voksenhjelp er bedre enn å vente eller etterforske alene.','adult'),
Q(10,'Alder betyr noe','Roblox bruker aldersgrupper og alderskontroller for å tilpasse innhold og kommunikasjon. Funksjoner og regler kan endres over tid og variere etter region.','Hvorfor kan feil alder på en konto være mer enn bare en liten profilfeil?',['Fordi alder kan påvirke hvilke sikkerhets- og kommunikasjonsvalg som gjelder','Fordi Roblox gir mer XP til riktig alder','Fordi fødselsdato bestemmer internetthastigheten'],0,'Alder kan inngå i hvordan plattformens sikkerhetsfunksjoner tilpasses.'),
Q(10,'9–12 år','For alderskontrollerte brukere i 9–12-gruppen har Roblox egne begrensninger. Enkelte kommunikasjonsfunksjoner krever foreldretillatelse.','Foreldrene dine har godkjent en funksjon. Hva betyr det for din egen dømmekraft?',['At alt som skjer i funksjonen dermed er trygt','At funksjonen kan brukes innen familiens rammer, men jeg må fortsatt vurdere mennesker og situasjoner','At sikkerhetsregler ikke lenger gjelder'],1,'Tillatelse til en funksjon er ikke en garanti for alt som skjer i den.'),
Q(10,'Foreldrekontroll','En koblet voksenkonto kan brukes til å styre blant annet innhold, kommunikasjon, skjermtid og pengebruk, avhengig av alder og gjeldende Roblox-regler.','Hva er den sterkeste måten å bruke foreldrekontroll på?',['Som tekniske grenser kombinert med samtaler om hvorfor grensene finnes','Som erstatning for alle samtaler om nettet','Ved å slå på flest mulig innstillinger uten å forstå dem'],0,'Tekniske kontroller fungerer best sammen med forståelse og kommunikasjon.'),
Q(10,'Filtre er ikke magi','Roblox bruker moderering og filtre, men ingen teknisk løsning kan garantere at alle mennesker eller alt innhold alltid er trygt.','En melding kom gjennom Roblox sine filtre. Hva kan du konkludere med?',['At meldingen er godkjent som helt trygg','At filteret ikke stoppet den, men jeg må fortsatt bruke egen dømmekraft','At avsenderen er identitetskontrollert'],1,'At noe passerer et teknisk filter er ikke det samme som en sikkerhetsgaranti.'),
Q(10,'Voksenoppdrag: sjekk kontoen','Hent en voksen og åpne Roblox sine foreldrekontroller sammen. Se på alder, innhold, kommunikasjon, skjermtid og pengebruk. Ikke endre noe uten at dere er enige.','Hva viser best at du faktisk forstår sikkerhetsinnstillingene etter gjennomgangen?',['At jeg kan forklare hva de viktigste innstillingene gjør, hvorfor vi bruker dem og hva de ikke kan beskytte mot','At jeg husker hvor alle knappene ligger','At jeg aldri trenger å spørre en voksen igjen'],0,'Målet er forståelse av både styrken og begrensningene i sikkerhetsverktøyene.','adult'),
Q(11,'Master: den hyggelige fremmede','Du har spilt med samme person i flere måneder. Personen kjenner favorittspillene dine, husker ting du har fortalt og virker hyggelig. Nå spør personen hvilken fotballklubb du spiller for, fordi dere kanskje bor i nærheten.','Hva er den beste vurderingen?',['Jeg kan si klubben fordi lang kontakt gjør identiteten ganske sikker','Jeg bør ikke dele klubben. Lang kontakt og mange riktige detaljer beviser fortsatt ikke hvem personen er','Jeg kan dele klubben hvis jeg først spør hvilken klubb personen spiller for'],1,'Tid og tillit på nett er ikke det samme som bekreftet identitet. En klubb kan også avsløre hvor du ofte befinner deg.','scenario'),
Q(11,'Master: den fantastiske premien','En venn sender deg en lenke til en side som ser nesten helt ut som Roblox. Vennen sier at han selv fikk en sjelden item der. Siden viser navnet ditt og sier at premien forsvinner om fem minutter.','Hva er den viktigste grunnen til å stoppe?',['At siden bruker tidspress. Hvis tiden hadde vært lengre, ville innlogging vært trygg','At kombinasjonen av ekstern lenke, innlogging, stor premie og tidspress kan være phishing selv om siden ser ekte ut og kommer fra en venn','At sjeldne items alltid er falske'],1,'En troverdig avsender eller profesjonell nettside gjør ikke en ekstern innlogging trygg. Flere varsellamper samtidig er spesielt viktig.','scenario'),
Q(11,'Master: ekte venn','En klassekamerat du kjenner godt skal hjelpe deg med avataren. Han trenger tilgang til kontoen og foreslår at du gir ham passordet i to minutter mens du sitter ved siden av.','Hva er den beste løsningen?',['La ham logge inn fordi du kan se hva han gjør','Logg inn selv og behold kontrollen over kontoen mens han forklarer hva du skal gjøre','Gi passordet og endre det etterpå'],1,'At du kjenner personen reduserer ikke behovet for å beskytte passordet. Hjelp kan gis uten å dele innlogging.','scenario'),
Q(11,'Master: hemmelig chat','En nettvenn sier at Roblox-chatten er upraktisk og foreslår en annen app. Personen sier at du gjerne kan spørre foreldrene først, men legger til at samtalen blir morsommere hvis voksne ikke følger med.','Hva bør veie tyngst i vurderingen?',['At personen sa at jeg kunne spørre foreldrene først, derfor er resten trygt','At ønsket om mer privat kontakt uten voksne fortsatt er et faresignal, så jeg bør stoppe og snakke med en voksen','At andre chat-apper alltid er farlige uansett hvem man snakker med'],1,'Et forslag kan inneholde noe som høres ansvarlig ut og samtidig ha et faresignal. Du må vurdere hele situasjonen.','scenario'),
Q(11,'Master: kjøpspress','Du har spart Robux til noe du ønsker deg. En annen pakke dukker opp med nedtelling og ser ut som et bedre kjøp. Du har faktisk nok Robux, og du trenger ikke spørre om mer penger.','Hva viser best at du forstår spillpsykologien?',['Jeg kan kjøpe med en gang fordi Robux allerede står på kontoen','Jeg vurderer om jeg ville valgt pakken uten nedtellingen, og tar en pause hvis tidspresset påvirker beslutningen','Jeg bør aldri kjøpe digitale ting'],1,'God dømmekraft betyr ikke at alle kjøp er feil. Det betyr at du klarer å skille ditt eget valg fra presset som designet skaper.','scenario'),
Q(11,'Master: du gjorde en feil','Du brukte en ekstern Roblox-lignende side og skrev inn passordet. Ingenting ser ut til å ha skjedd, tofaktor er aktivert, og kontoen fungerer fortsatt normalt.','Hva er den beste handlingen nå?',['Vente og se siden tofaktor sannsynligvis stoppet alt','Fortelle en voksen med en gang, sikre kontoen gjennom de riktige kanalene og behandle passordet som kompromittert','Bare endre passordet hvis kontoen senere begynner å oppføre seg merkelig'],1,'At du ikke ser skade ennå betyr ikke at innloggingen er trygg. Rask hjelp og sikring kan hindre at problemet utvikler seg.','adult')
];
let state={done:[],wrong:0,adult:[]},current=null;
try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
state.done=[...new Set((state.done||[]).filter(Number.isInteger))];state.adult=[...new Set((state.adult||[]).filter(Number.isInteger))];
const $=id=>document.getElementById(id);const chapterIndices=c=>lessons.map((l,i)=>l.ch===c?i:-1).filter(i=>i>=0);const chapterDone=c=>chapterIndices(c).filter(i=>state.done.includes(i)).length;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function unlocked(c){return c===0||chapterDone(c-1)===chapterIndices(c-1).length}
function render(){const pct=Math.round(100*state.done.length/lessons.length);$('progressText').textContent=`${state.done.length}/${lessons.length} oppdrag fullført`;$('scoreText').textContent=`${pct}% gjennomført`;$('adultText').textContent=`${state.adult.length} voksenoppdrag`;$('bar').style.width=pct+'%';$('chapterGrid').innerHTML=chapters.map((c,i)=>{const d=chapterDone(i),n=chapterIndices(i).length,l=!unlocked(i);return `<button class="card chapter ${l?'locked':''}" ${l?'disabled':''} onclick="openChapter(${i})"><div style="font-size:34px">${c[0]}</div><h3>${i+1}. ${c[1]}</h3><p class="muted">${c[2]}</p><b>${d}/${n}</b><div class="progress"><span style="width:${100*d/n}%"></span></div></button>`}).join('')}
function openChapter(c){if(!unlocked(c))return;const idx=chapterIndices(c).find(i=>!state.done.includes(i))??chapterIndices(c)[0];openLesson(idx)}
function openLesson(i){current=i;if(window.IANSRobloxFocus)window.IANSRobloxFocus.enter();const l=lessons[i],done=state.done.includes(i);$('lesson').hidden=false;$('lesson').className='card '+(l.type==='adult'?'adult':l.type==='scenario'?'scenario':'');$('lesson').innerHTML=`<div><b>${chapters[l.ch][0]} KAPITTEL ${l.ch+1} · OPPDRAG ${chapterIndices(l.ch).indexOf(i)+1}/${chapterIndices(l.ch).length}</b>${l.type==='adult'?'<b> · 👨‍👦 VOKSENOPPDRAG</b>':l.type==='scenario'?'<b> · 🧭 SCENARIO</b>':''}</div><h2>${l.t}</h2><p class="muted" style="line-height:1.65">${l.x}</p><h3>${l.q}</h3><div class="answers">${l.a.map((a,j)=>`<button class="answer" ${done?'disabled':''} onclick="answer(${j})">${a}</button>`).join('')}</div><div id="feedback" style="margin-top:14px">${done?'✅ '+l.why:''}</div><div class="actions"><button class="btn" onclick="window.IANSRobloxShowChapters?IANSRobloxShowChapters():document.getElementById('chapters').scrollIntoView()">Alle kapitler</button>${done?'<button class="btn" onclick="nextLesson()">Neste →</button>':''}</div>`;$('lesson').scrollIntoView({behavior:'smooth',block:'start'})}
function answer(j){if(current===null||state.done.includes(current))return;const l=lessons[current],f=$('feedback');if(j===l.c){state.done.push(current);if(l.type==='adult')state.adult.push(current);save();render();openLesson(current);if(window.IANSRobloxFocus)window.IANSRobloxFocus.refresh();f.className='good'}else{state.wrong++;save();f.className='bad';f.textContent='Ikke helt. Tenk på hvorfor noen ønsker at du skal velge dette, og prøv igjen.'}}
function nextLesson(){
  const l=lessons[current],arr=chapterIndices(l.ch),pos=arr.indexOf(current);

  if(pos<arr.length-1){
    return openLesson(arr[pos+1]);
  }

  render();

  if(l.ch<chapters.length-1&&unlocked(l.ch+1)){
    return openChapter(l.ch+1);
  }

  // Siste oppdrag i siste kapittel:
  // behold all progresjon og åpne kursmappen hvor diplomet ligger.
  if(state.done.length===lessons.length){
    $('lesson').hidden=true;

    if(window.IANSRobloxFocus){
      window.IANSRobloxFocus.exit?.();
    }

    if(window.IANSRobloxOpenKnowledge){
      return window.IANSRobloxOpenKnowledge();
    }

    const knowledge=document.getElementById('knowledge');
    if(knowledge){
      knowledge.scrollIntoView({behavior:'smooth',block:'start'});
    }
  }
}
render();
