const { TableClient } = require('@azure/data-tables');
const { BlobServiceClient } = require('@azure/storage-blob');
const crypto = require('crypto');

const TABLE='IansSameieRegistrations';
const CONTAINER='ians-sameie-onboarding';
function json(status,body){return{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'},body:JSON.stringify(body)}}
function clean(v,n=254){return String(v||'').trim().slice(0,n)}
function principal(req){try{const r=req.headers['x-ms-client-principal'];return r?JSON.parse(Buffer.from(r,'base64').toString('utf8')):null}catch{return null}}
function storage(){return process.env.IANS_BOOKING_STORAGE||process.env.AzureWebJobsStorage}
function safeName(v){return clean(v,120).replace(/[^A-Za-z0-9._-]+/g,'-').replace(/-+/g,'-')||'file'}
function decodeFile(f,maxBytes,allowed){if(!f||!f.data)return null;const type=clean(f.type,100).toLowerCase();if(!allowed.some(x=>type===x||type.startsWith(x)))throw new Error('Filtypen er ikke tillatt.');const buf=Buffer.from(String(f.data).replace(/^data:[^;]+;base64,/,''),'base64');if(!buf.length||buf.length>maxBytes)throw new Error('Filen er for stor.');return{buf,type,name:safeName(f.name)}}
async function upload(container,prefix,file){if(!file)return'';const blobName=`${prefix}/${crypto.randomUUID()}-${file.name}`;const bc=container.getBlockBlobClient(blobName);await bc.uploadData(file.buf,{blobHTTPHeaders:{blobContentType:file.type}});return blobName}
module.exports=async function(context,req){try{const p=principal(req);if(!p){context.res=json(401,{ok:false,error:'Logg inn med Microsoft før du registrerer et sameie.'});return}const b=req.body||{};const sameieName=clean(b.sameieName,180),orgNumber=clean(b.orgNumber,30),address=clean(b.address,180),postalCode=clean(b.postalCode,12),city=clean(b.city,80),units=Math.max(0,Math.min(5000,Number(b.units||0))),contactName=clean(b.contactName,120),contactEmail=clean(b.contactEmail,254).toLowerCase(),contactPhone=clean(b.contactPhone,40),contactRole=clean(b.contactRole,80),website=clean(b.website,180),notes=clean(b.notes,2000);if(!sameieName||!contactName||!contactEmail.includes('@')){context.res=json(400,{ok:false,error:'Sameienavn, kontaktperson og gyldig e-post må fylles ut.'});return}if(!b.confirmedAuthority){context.res=json(400,{ok:false,error:'Du må bekrefte at du har fullmakt til å sende inn opplysningene.'});return}let members=[];if(Array.isArray(b.boardMembers))members=b.boardMembers.slice(0,20).map(x=>({name:clean(x.name,120),email:clean(x.email,254).toLowerCase(),role:clean(x.role,80)})).filter(x=>x.name||x.email);const image=decodeFile(b.profileImage,5*1024*1024,['image/']);const residents=decodeFile(b.residentList,12*1024*1024,['text/csv','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']);const cs=storage();if(!cs)throw new Error('Lagring er ikke konfigurert.');const tc=TableClient.fromConnectionString(cs,TABLE);await tc.createTable().catch(e=>{if(e.statusCode!==409)throw e});const bs=BlobServiceClient.fromConnectionString(cs);const cc=bs.getContainerClient(CONTAINER);await cc.createIfNotExists();const id=crypto.randomUUID(),prefix=`${new Date().toISOString().slice(0,10)}/${id}`;const [profileImageBlob,residentListBlob]=await Promise.all([upload(cc,prefix,image),upload(cc,prefix,residents)]);const now=new Date().toISOString();await tc.createEntity({partitionKey:'pending',rowKey:id,status:'pending',sameieName,orgNumber,address,postalCode,city,units,contactName,contactEmail,contactPhone,contactRole,website,notes,boardMembers:JSON.stringify(members),profileImageBlob,residentListBlob,submittedAt:now,submittedBy:clean(p.userDetails,254),submittedById:clean(p.userId,254)});context.res=json(201,{ok:true,id,status:'pending',message:'Sameiet er sendt til godkjenning. Det opprettes ikke før forespørselen er godkjent.'});}catch(e){context.log.error(e);context.res=json(500,{ok:false,error:e.message&&/Fil|Filen/.test(e.message)?e.message:'Kunne ikke sende registreringen akkurat nå.'})}};
