(() => {
'use strict';
const $=id=>document.getElementById(id), board=$('board'), actions=$('actions'), status=$('status');
const kind=document.body.dataset.game;
let cleanup=()=>{},handleKey=()=>{},run=0,mode=1,record=0;
const titles={
 'merge-2048':['2048 Reactor','Skyv hele brettet og slå sammen like tall. Planlegg flere trekk fremover og nå 2048.','Sveip på brettet, bruk pilknappene eller piltastene. Bare like tall kan slås sammen.'],
 'connect-four':['Fire på rad','Utfordre datamaskinen. Bygg feller, blokker motstanderen og få fire på rad.','Du er gul. Velg en kolonne. Fire vannrett, loddrett eller diagonalt vinner.'],
 'mine-lab':['Mine Lab','Bruk tallene til å finne de skjulte minene. Ett feil valg kan avslutte runden.','Tallet viser miner i de åtte naborutene. Bytt mellom Åpne og Flagg. Første åpning er trygg.'],
 'sudoku-lab':['Sudoku Lab','Et lite brett med store tankenøtter. Løs et 6 × 6-sudoku i ditt eget tempo.','Hver rad, kolonne og boks på 2 × 3 skal inneholde tallene 1–6 én gang hver. Velg en rute og deretter et tall.'],
 'lights-out':['Lysjakten','Slukk hele energinettet. Hvert trykk snur både ruten og naboene.','Trykk på en rute for å snu den og naboene over, under og til sidene. Alle brett er løsbare.'],
 'slide-puzzle':['Skyvepuslespill','Få tallene i riktig rekkefølge med færrest mulig trekk.','Trykk på en brikke ved siden av hullet. Målet er 1, 2, 3 … fra øverst til venstre, med hullet nederst til høyre.'],
 'code-breaker':['Kodeknekkeren','Knekk en hemmelig firesifret kode med logikk og tilbakemeldinger.','Alle sifre i koden er forskjellige. Riktig plass = riktig siffer på riktig sted. Feil plass = riktig siffer et annet sted.'],
 'word-hunt':['Ordjakten','Finn ordene som skjuler seg i bokstavnettet. Se etter både rette og diagonale ord.','Trykk på første og siste bokstav i et ord. Ordene kan også stå baklengs. Ingen trekking er nødvendig.'],
 'maze-run':['Labyrintjakten','Finn veien ut av en ny labyrint. Planlegg ruten og unngå blindveiene.','Du er den grønne ruten. Nå den lilla utgangen med færrest mulig steg. Bruk knappene, piltastene eller sveip.'],
 'target-rush':['Target Rush','Treff de grønne målene før tiden går ut. La de rosa lokkemålene være.','En runde varer i 30 sekunder. Grønt mål: +10. Rosa mål eller bom: −5. Raskere mål på høyere vanskelighetsgrad.']
};
const info=titles[kind];$('title').textContent=info[0];$('description').textContent=info[1];$('help').textContent=info[2];document.title=info[0]+' · IANS Games';
function say(t){status.textContent=t}
function stat(t){$('stat').textContent=t}
function save(v){record=Math.max(record,v);$('record').textContent='Beste: '+record;try{localStorage.setItem('iansArcade:'+kind+':'+mode,record)}catch{}}
function button(text,fn,cls=''){const b=document.createElement('button');b.textContent=text;b.className=cls;b.onclick=fn;return b}
function grid(n,extra=''){board.className='grid '+extra;board.style.gridTemplateColumns=`repeat(${n},1fr)`;board.replaceChildren()}
function cell(text,fn,cls=''){const b=button(text,fn,'cell '+cls);board.append(b);return b}
function pad(fn){const p=document.createElement('div');p.className='control-pad';for(const [label,d] of [['↑','up'],['←','left'],['↓','down'],['→','right']])p.append(button(label,()=>fn(d)));actions.append(p);handleKey=e=>{const d={ArrowUp:'up',ArrowLeft:'left',ArrowDown:'down',ArrowRight:'right'}[e.key];if(d){e.preventDefault();fn(d)}};let start;board.onpointerdown=e=>{start={x:e.clientX,y:e.clientY};board.setPointerCapture(e.pointerId)};board.onpointerup=e=>{if(!start)return;const x=e.clientX-start.x,y=e.clientY-start.y;start=null;if(Math.max(Math.abs(x),Math.abs(y))>24)fn(Math.abs(x)>Math.abs(y)?x>0?'right':'left':y>0?'down':'up')};board.onpointercancel=()=>start=null;board.style.touchAction='none'}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function start(){cleanup();cleanup=()=>{};handleKey=()=>{};run++;mode=Number($('mode').value);record=0;try{record=Number(localStorage.getItem('iansArcade:'+kind+':'+mode))||0}catch{}$('record').textContent='Beste: '+record;board.replaceChildren();board.className='';board.style.gridTemplateColumns='';board.style.touchAction='manipulation';board.onpointerdown=board.onpointerup=board.onpointercancel=null;actions.replaceChildren();stat('');say('');games[kind]()}
const games={};
games['merge-2048']=()=>{let a=Array(16).fill(0),points=0,over=false,won=false;const goal=[512,2048,4096][mode];function spawn(){const empty=a.map((v,i)=>v?null:i).filter(i=>i!==null);if(empty.length)a[empty[Math.floor(Math.random()*empty.length)]]=Math.random()<.9?2:4}function draw(){grid(4);a.forEach(v=>{const b=cell(v||'',()=>{},'tile-2048');b.dataset.value=v;b.setAttribute('aria-label',v?String(v):'Tom rute')});stat(points+' poeng · mål '+goal)}function move(d){if(over)return;const old=a.join();for(let line=0;line<4;line++){let ids=Array.from({length:4},(_,i)=>d==='left'?line*4+i:d==='right'?line*4+3-i:d==='up'?i*4+line:(3-i)*4+line);let vals=ids.map(i=>a[i]).filter(Boolean),out=[];for(let i=0;i<vals.length;i++){if(vals[i]===vals[i+1]){out.push(vals[i]*2);points+=vals[i]*2;i++}else out.push(vals[i])}ids.forEach((id,i)=>a[id]=out[i]||0)}if(old===a.join())return;spawn();save(points);draw();if(!won&&a.some(v=>v>=goal)){won=true;say('Målet nådd! Fortsett og sett ny rekord.')}if(a.every(Boolean)&&a.every((v,i)=>(i%4===3||a[i+1]!==v)&&(i>=12||a[i+4]!==v))){over=true;say('Ingen flere trekk. '+points+' poeng — prøv et nytt brett.')}}spawn();spawn();draw();say('Bygg store tall i et hjørne. Mål: '+goal+'.');pad(move)};
games['connect-four']=()=>{let a=Array(42).fill(0),over=false,busy=false,timer;cleanup=()=>clearTimeout(timer);function drop(b,col,p){for(let r=5;r>=0;r--)if(!b[r*7+col]){b[r*7+col]=p;return r*7+col}return -1}function win(b,p){for(let r=0;r<6;r++)for(let c=0;c<7;c++)for(const [dr,dc]of[[0,1],[1,0],[1,1],[1,-1]]){if(r+3*dr>5||c+3*dc<0||c+3*dc>6)continue;if([0,1,2,3].every(k=>b[(r+k*dr)*7+c+k*dc]===p))return true}return false}function valid(b){return [3,2,4,1,5,0,6].filter(c=>!b[c])}function evaluate(b){let s=0;for(let r=0;r<6;r++)for(let c=0;c<7;c++)for(const [dr,dc]of[[0,1],[1,0],[1,1],[1,-1]]){if(r+3*dr>5||c+3*dc<0||c+3*dc>6)continue;const w=[0,1,2,3].map(k=>b[(r+k*dr)*7+c+k*dc]),ai=w.filter(v=>v===2).length,hu=w.filter(v=>v===1).length;if(!hu)s+=[0,1,8,70,10000][ai];if(!ai)s-=[0,1,10,90,10000][hu]}return s}function minimax(b,depth,max,alpha,beta){if(win(b,2))return 100000+depth;if(win(b,1))return -100000-depth;const cols=valid(b);if(!depth||!cols.length)return evaluate(b);let value=max?-Infinity:Infinity;for(const c of cols){const next=b.slice();drop(next,c,max?2:1);const s=minimax(next,depth-1,!max,alpha,beta);value=max?Math.max(value,s):Math.min(value,s);if(max)alpha=Math.max(alpha,value);else beta=Math.min(beta,value);if(beta<=alpha)break}return value}function draw(){grid(7);a.forEach((v,i)=>{const b=cell(v?'●':'·',()=>play(i%7),v===1?'gold':v===2?'red':'');b.setAttribute('aria-label','Kolonne '+(i%7+1)+', '+(v===1?'din brikke':v===2?'datamaskin':'tom'));b.disabled=over||busy});stat('Du: gul · Datamaskin: rosa')}function check(p){if(win(a,p)){over=true;say(p===1?'Du vant! Fire på rad.':'Datamaskinen vant. Prøv å blokkere tre på rad.');if(p===1)save(record+1)}else if(a.every(Boolean)){over=true;say('Uavgjort — brettet er fullt.')}}function play(c){if(over||busy||a[c])return;drop(a,c,1);check(1);if(over){draw();return}busy=true;say('Datamaskinen tenker …');draw();timer=setTimeout(()=>{const cols=valid(a);let choice=cols[0],best=-Infinity;for(const c of cols){const b=a.slice();drop(b,c,2);const s=minimax(b,[0,2,4][mode],false,-Infinity,Infinity);if(s>best){best=s;choice=c}}drop(a,choice,2);busy=false;check(2);if(!over)say('Din tur.');draw()},220)}say('Du starter. Velg en kolonne.');draw()};
games['mine-lab']=()=>{const n=8,total=[8,12,16][mode];let mines=new Set(),opened=new Set(),flags=new Set(),first=true,over=false,flag=false;const near=i=>{const out=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){let r=Math.floor(i/n)+dr,c=i%n+dc;if((dr||dc)&&r>=0&&r<n&&c>=0&&c<n)out.push(r*n+c)}return out};const count=i=>near(i).filter(j=>mines.has(j)).length;function draw(){grid(n,'mines');for(let i=0;i<n*n;i++){const reveal=opened.has(i)||(over&&mines.has(i)),text=flags.has(i)&&!reveal?'⚑':reveal?mines.has(i)?'✹':count(i)||'':'';const b=cell(text,()=>tap(i),reveal?'revealed':'');b.setAttribute('aria-label',`Rute ${i+1}: ${text||'lukket'}`);b.disabled=over||opened.has(i)}stat(flags.size+' / '+total+' flagg · '+opened.size+' åpne')}function tap(i){if(over||opened.has(i))return;if(flag){if(flags.has(i))flags.delete(i);else if(flags.size<total)flags.add(i);draw();return}if(flags.has(i))return;if(first){const safe=new Set([i,...near(i)]);mines=new Set(shuffle(Array.from({length:n*n},(_,j)=>j).filter(j=>!safe.has(j))).slice(0,total));first=false}if(mines.has(i)){over=true;say('En mine! Bruk nabotallene i neste runde.');draw();return}const queue=[i];while(queue.length){const q=queue.pop();if(opened.has(q)||flags.has(q)||mines.has(q))continue;opened.add(q);if(!count(q))queue.push(...near(q))}if(opened.size===n*n-total){over=true;save(record+1);say('Alle trygge ruter funnet!')}draw()}const toggle=button('Modus: Åpne',()=>{flag=!flag;toggle.textContent='Modus: '+(flag?'Flagg ⚑':'Åpne');toggle.setAttribute('aria-pressed',flag)});actions.append(toggle);say('Første åpning er trygg. '+total+' miner er skjult.');draw()};
// A solved Latin-pattern sudoku is shuffled by valid row/column/symbol permutations.
games['sudoku-lab']=()=>{const symbols=shuffle([1,2,3,4,5,6]),rows=shuffle([0,1,2]).flatMap(b=>shuffle([b*2,b*2+1])),cols=shuffle([0,1]).flatMap(s=>shuffle([s*3,s*3+1,s*3+2]));const solution=rows.flatMap(r=>cols.map(c=>symbols[(r*3+Math.floor(r/2)+c)%6]));let values=solution.slice(),selected=-1,done=false;function candidates(b,i){return [1,2,3,4,5,6].filter(v=>!b.some((x,j)=>x===v&&(Math.floor(j/6)===Math.floor(i/6)||j%6===i%6||(Math.floor(j/12)===Math.floor(i/12)&&Math.floor(j%6/3)===Math.floor(i%6/3)))))}function solutions(b){let index=-1,opts;for(let i=0;i<36;i++)if(!b[i]){const c=candidates(b,i);if(!c.length)return 0;if(index<0||c.length<opts.length){index=i;opts=c}}if(index<0)return 1;let result=0;for(const v of opts){b[index]=v;result+=solutions(b);if(result>=2)break}b[index]=0;return result}let removed=0;for(const i of shuffle(Array.from({length:36},(_,i)=>i))){const v=values[i];values[i]=0;if(solutions(values.slice())!==1)values[i]=v;else removed++;if(removed>=[14,21,25][mode])break}const fixed=values.map(Boolean);function draw(){grid(6,'sudoku');values.forEach((v,i)=>{const b=cell(v||'',()=>{if(!fixed[i]&&!done){selected=i;draw()}},fixed[i]?'fixed':selected===i?'selected':'');if(Math.floor(i/6)%2===1)b.style.borderBottom='3px solid #6d94ae';b.setAttribute('aria-label',`Rad ${Math.floor(i/6)+1}, kolonne ${i%6+1}, ${v||'tom'}`)});stat(values.filter(Boolean).length+' / 36 fylt')}function enter(v){if(selected<0||done)return;values[selected]=v;draw();if(values.every((x,i)=>x===solution[i])){done=true;save(record+1);say('Løst! Alle rader, kolonner og bokser stemmer.')}else say('Fortsett — bruk hver verdi én gang i raden, kolonnen og boksen.')}for(let v=1;v<=6;v++)actions.append(button(v,()=>enter(v)));actions.append(button('Slett',()=>enter(0)));actions.append(button('Sjekk',()=>{const errors=values.filter((v,i)=>v&&v!==solution[i]).length;say(errors?errors+' rute(r) stemmer ikke ennå.':'Alle utfylte ruter stemmer.')}));handleKey=e=>{if(/^[1-6]$/.test(e.key))enter(+e.key);if(e.key==='Backspace'){e.preventDefault();enter(0)}};say('Velg en tom rute. Brettet har én løsning.');draw()};
games['lights-out']=()=>{const n=[4,5,6][mode];let a=Array(n*n).fill(false),moves=0,done=false;function flip(i){for(const j of [i,i%n>0?i-1:-1,i%n<n-1?i+1:-1,i-n,i+n])if(j>=0&&j<n*n)a[j]=!a[j]}for(const i of shuffle(Array.from({length:n*n},(_,i)=>i)).slice(0,[7,12,20][mode]))flip(i);if(!a.some(Boolean))flip(0);function draw(){grid(n);a.forEach((v,i)=>{const b=cell(v?'✦':'·',()=>{if(done)return;flip(i);moves++;draw();if(!a.some(Boolean)){done=true;save(Math.max(1,1000-moves*10));say('Alle lys er slukket! '+moves+' trekk.')}} ,v?'on':'');b.setAttribute('aria-label',`Lys ${i+1}: ${v?'på':'av'}`);b.setAttribute('aria-pressed',v)});stat(moves+' trekk · '+a.filter(Boolean).length+' lys på')}say('Slukk alle lysene. Tenk på hva hvert trykk snur.');draw()};
games['slide-puzzle']=()=>{const n=[3,4,5][mode],size=n*n;let a=Array.from({length:size},(_,i)=>(i+1)%size),empty=size-1,moves=0,done=false,previous=-1;const adjacent=i=>[i%n>0?i-1:-1,i%n<n-1?i+1:-1,i-n,i+n].filter(j=>j>=0&&j<size);for(let k=0;k<[70,180,350][mode];k++){const pool=adjacent(empty).filter(i=>i!==previous),i=pool[Math.floor(Math.random()*pool.length)];[a[i],a[empty]]=[a[empty],a[i]];previous=empty;empty=i}if(a.every((v,i)=>v===(i+1)%size)){const i=adjacent(empty)[0];[a[i],a[empty]]=[a[empty],a[i]];empty=i}function draw(){grid(n);a.forEach((v,i)=>{const b=cell(v||'',()=>move(i),v===i+1?'fixed':'');b.setAttribute('aria-label',v?'Brikke '+v:'Tom plass');b.disabled=!v||done});stat(moves+' trekk')}function move(i){if(done||!adjacent(empty).includes(i))return;[a[i],a[empty]]=[a[empty],a[i]];empty=i;moves++;draw();if(a.every((v,i)=>v===(i+1)%size)){done=true;save(Math.max(1,5000-moves*5));say('Riktig rekkefølge! '+moves+' trekk.')}}say('Sorter tallene. Brettet er stokket med lovlige trekk.');draw()};
games['code-breaker']=()=>{const digits=[6,8,10][mode],max=[10,8,7][mode],secret=shuffle(Array.from({length:digits},(_,i)=>String(i))).slice(0,4);let turn=0,done=false;const history=document.createElement('div');board.append(history);const form=document.createElement('form'),input=document.createElement('input');input.inputMode='numeric';input.autocomplete='off';input.maxLength=4;input.placeholder='Fire forskjellige sifre';input.setAttribute('aria-label','Kodeforslag, fire forskjellige sifre');const submit=button('Test kode',()=>{});submit.type='submit';form.append(input,submit);actions.append(form);form.onsubmit=e=>{e.preventDefault();if(done)return;const guess=input.value.trim().split('');if(guess.length!==4||new Set(guess).size!==4||guess.some(v=>!/^\d$/.test(v)||Number(v)>=digits)){say(`Skriv fire forskjellige sifre fra 0 til ${digits-1}.`);return}turn++;const exact=guess.filter((v,i)=>v===secret[i]).length,other=guess.filter(v=>secret.includes(v)).length-exact;const row=document.createElement('div');row.className='code-row';const left=document.createElement('b'),right=document.createElement('span');left.textContent=guess.join(' ');right.textContent=`${exact} riktig plass · ${other} feil plass`;row.append(left,right);history.append(row);input.value='';stat(turn+' / '+max+' forsøk');if(exact===4){done=true;save((max-turn+1)*100);say('Koden er knekt på '+turn+' forsøk!')}else if(turn===max){done=true;say('Ingen forsøk igjen. Koden var '+secret.join(' ')+'.')}else say('Bruk svaret til å utelukke kombinasjoner.');input.disabled=submit.disabled=done};stat('0 / '+max+' forsøk');say(`Koden har fire forskjellige sifre fra 0 til ${digits-1}. Du har ${max} forsøk.`)};
games['word-hunt']=()=>{const n=[7,8,9][mode],words=['LASER','ROBOT','KODE','ORBIT','NEON','PLANET','RAKETT','STJERNE'].slice(0,[4,6,8][mode]);const directions=mode===0?[[0,1],[1,0]]:[[0,1],[1,0],[1,1],[-1,1],[0,-1],[-1,0],[-1,-1],[1,-1]];let a,placements;for(let attempt=0;attempt<100;attempt++){a=Array(n*n).fill('');placements=[];for(const word of words.slice().sort((a,b)=>b.length-a.length)){const options=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++)for(const [dr,dc]of directions){const ids=Array.from(word,(_,k)=>[r+k*dr,c+k*dc]);if(ids.every(([rr,cc],k)=>rr>=0&&rr<n&&cc>=0&&cc<n&&(!a[rr*n+cc]||a[rr*n+cc]===word[k])))options.push(ids.map(([rr,cc])=>rr*n+cc))}if(!options.length)break;const ids=options[Math.floor(Math.random()*options.length)];ids.forEach((id,k)=>a[id]=word[k]);placements.push({word,ids})}if(placements.length===words.length)break}a=a.map(v=>v||'ABCDEFGHIJKLMNOPQRSTUVWXYZ'[Math.floor(Math.random()*26)]);let selected=null,found=new Set(),highlight=new Set();const list=document.createElement('div');list.className='wordlist';actions.append(list);function draw(){list.replaceChildren();words.forEach(w=>{const s=document.createElement('span');s.textContent=w;s.className=found.has(w)?'found':'';list.append(s)});grid(n);a.forEach((v,i)=>cell(v,()=>tap(i),selected===i?'selected':highlight.has(i)?'word':''));stat(found.size+' / '+words.length+' ord')}function tap(i){if(found.size===words.length)return;if(selected===null){selected=i;draw();return}const r=Math.floor(selected/n),c=selected%n,dr=Math.floor(i/n)-r,dc=i%n-c;const straight=dr===0||dc===0||Math.abs(dr)===Math.abs(dc),len=Math.max(Math.abs(dr),Math.abs(dc))+1;let ids=straight?Array.from({length:len},(_,k)=>(r+k*Math.sign(dr))*n+c+k*Math.sign(dc)):[],text=ids.map(j=>a[j]).join('');const word=words.find(w=>!found.has(w)&&(text===w||text.split('').reverse().join('')===w));if(word){found.add(word);ids.forEach(j=>highlight.add(j));say('Fant '+word+'!');if(found.size===words.length){save(record+1);say('Alle ordene funnet!')}}else say('Ikke et av ordene. Velg første og siste bokstav.');selected=null;draw()}say('Finn ordene nedenfor. Trykk på begge endene av ordet.');draw()};
games['maze-run']=()=>{const n=[11,15,19][mode],a=Array(n*n).fill(1),stack=[n+1];a[n+1]=0;while(stack.length){const i=stack[stack.length-1],r=Math.floor(i/n),c=i%n,opts=shuffle([[0,2],[0,-2],[2,0],[-2,0]]).filter(([dr,dc])=>r+dr>0&&r+dr<n-1&&c+dc>0&&c+dc<n-1&&a[(r+dr)*n+c+dc]);if(!opts.length){stack.pop();continue}const [dr,dc]=opts[0],j=(r+dr)*n+c+dc;a[i+dr/2*n+dc/2]=a[j]=0;stack.push(j)}let player=n+1,exit=n*n-n-2,moves=0,done=false;function draw(){grid(n,'maze');a.forEach((v,i)=>{const d=document.createElement('div');d.className='cell '+(i===player?'player':i===exit?'exit':v?'wall':'path');d.textContent=i===player?'●':i===exit?'◆':'';board.append(d)});stat(moves+' steg');board.setAttribute('aria-label','Labyrint. Rad '+(Math.floor(player/n)+1)+', kolonne '+(player%n+1))}function move(d){if(done)return;const delta={up:-n,down:n,left:-1,right:1}[d],next=player+delta;if(next<0||next>=a.length||a[next])return;player=next;moves++;draw();if(player===exit){done=true;save(Math.max(1,5000-moves*5));say('Du fant utgangen på '+moves+' steg!')}}say('Finn den lilla utgangen nederst til høyre.');draw();pad(move)};
games['target-rush']=()=>{let points=0,remaining=30,active=false,timer,next,ends,stamp=0;const arena=document.createElement('div');arena.className='target-board';board.append(arena);const startButton=button('Start 30 sekunder',begin,'primary');actions.append(startButton);const duration=[1500,1050,740][mode];function draw(){stat(points+' poeng · '+remaining+' sekunder')}function end(message){active=false;clearInterval(timer);clearTimeout(next);arena.replaceChildren();save(points);say(message||'Tiden er ute! '+points+' poeng.');startButton.disabled=false;startButton.textContent='Spill igjen'}function spawn(){if(!active)return;arena.replaceChildren();const generation=++stamp;const spots=shuffle([[18,20],[50,20],[82,20],[18,50],[50,50],[82,50],[18,80],[50,80],[82,80]]);for(let i=0;i<(mode===0?2:3);i++){const good=i===0,b=button(good?'✦':'×',()=>{} ,'target'+(good?'':' decoy'));b.style.left=spots[i][0]+'%';b.style.top=spots[i][1]+'%';b.setAttribute('aria-label',good?'Grønt mål':'Rosa lokkemål');b.onpointerdown=e=>{e.preventDefault();e.stopPropagation();if(!active||generation!==stamp)return;if(performance.now()>=ends){end();return}points=Math.max(0,points+(good?10:-5));draw();clearTimeout(next);spawn()};arena.append(b)}next=setTimeout(()=>{if(active){points=Math.max(0,points-2);draw();spawn()}},duration)}function begin(){active=true;points=0;remaining=30;ends=performance.now()+30000;startButton.disabled=true;say('Treff grønt. Unngå rosa!');draw();spawn();timer=setInterval(()=>{remaining=Math.max(0,Math.ceil((ends-performance.now())/1000));draw();if(!remaining)end()},100)}arena.onpointerdown=e=>{if(active&&e.target===arena){points=Math.max(0,points-5);draw()}};const hide=()=>{if(document.hidden&&active)end('Runden ble avsluttet fordi du byttet fane. Start en ny runde når du er klar.')};document.addEventListener('visibilitychange',hide);cleanup=()=>{active=false;clearInterval(timer);clearTimeout(next);document.removeEventListener('visibilitychange',hide)};draw();say('Klar? Du har 30 sekunder.')};
$('new').onclick=start;$('mode').onchange=start;document.addEventListener('keydown',e=>{if(e.target.matches('input,select,button'))return;handleKey(e)});document.addEventListener('click',e=>{if(e.target.tagName==='BUTTON')e.target.blur()});start();
})();
