from pathlib import Path
p=Path('tools/file-commander/index.html')
s=p.read_text()
old='<button class="btn smart" id="refresh">↻ Oppdater</button>'
new='<button class="btn smart" id="refresh">↻ Oppdater</button><button class="btn primary" id="ai">✦ IANS AI</button>'
if old in s and 'id="ai"' not in s:s=s.replace(old,new,1)
needle="$('#help').onclick="
addon=r'''async function openAI(){const inventory=[];for(const side of ['left','right'])for(const x of state[side].items)inventory.push({side,name:x.name,kind:x.kind,size:x.size||0,modified:x.modified||0});if(!inventory.length)return setStatus('Åpne minst én mappe før AI-analyse.');openDialog('<h3>✦ IANS File Commander AI</h3><p class="legend">AI får kun katalogmetadata du ser her – fil-/mappenavn, type, størrelse og dato. Filinnhold sendes ikke.</p><textarea id="aiq" rows="4" placeholder="F.eks. Hvor bruker jeg mest plass, og hvordan bør dette organiseres?"></textarea><div class="actions"><button class="btn primary" id="airun">Analyser metadata</button></div><div id="aiout"></div>');$('#airun').onclick=async()=>{const q=$('#aiq').value.trim();$('#airun').disabled=true;$('#aiout').innerHTML='<p class="legend">IANS AI analyserer '+inventory.length+' katalogelementer…</p>';try{const r=await fetch('/api/file-commander-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,inventory})});const raw=await r.text();let b={};try{b=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(b.error||('API svarte '+r.status+(raw?' · '+raw.slice(0,160):'')));if(!b.analysis)throw new Error('AI API returnerte ikke en analyse.');$('#aiout').innerHTML='<div class="preview"><pre>'+esc(b.analysis)+'</pre></div><p class="legend">AI har kun foreslått tiltak. Ingen filer er endret.</p>'}catch(e){$('#aiout').innerHTML='<div class="report"><div><b>AI utilgjengelig</b><br>'+esc(e.message)+'</div></div>'}finally{$('#airun').disabled=false}}}$('#ai').onclick=openAI;
'''
if needle in s and "function openAI()" not in s:s=s.replace(needle,addon+needle,1)
# Replace sync preview with executable, directional sync plan.
start="function syncPlan(){"
end="}document.querySelectorAll('.pane')"
if start in s and end in s:
    a=s.index(start); b=s.index(end,a)
    sync=r'''function syncPlan(){if(!state.left.handle||!state.right.handle)return setStatus('Åpne begge mapper først.');const L=new Map(state.left.items.map(x=>[x.name,x])),R=new Map(state.right.items.map(x=>[x.name,x])),actions=[];for(const [n,a]of L){const b=R.get(n);if(!b)actions.push({dir:'lr',name:n,item:a,label:'Venstre → Høyre'});else if(a.kind!==b.kind||a.size!==b.size)actions.push({dir:'conflict',name:n,item:a,label:'Avvik – kontroller manuelt'})}for(const [n,b]of R)if(!L.has(n))actions.push({dir:'rl',name:n,item:b,label:'Høyre → Venstre'});window.__iansSyncActions=actions;openDialog('<h3>Synkroniseringsplan</h3><div class="report">'+(actions.length?actions.map((x,i)=>'<div><b>'+esc(x.label)+'</b> · '+esc(x.name)+(x.dir==='conflict'?'':' <label style="float:right"><input class="syncPick" type="checkbox" data-i="'+i+'" checked> Utfør</label>')+'</div>').join(''):'<div>Mappene ser synkroniserte ut på navn/type/størrelse.</div>')+'</div>'+(actions.some(x=>x.dir!=='conflict')?'<div class="actions"><button class="btn primary" id="executeSync">Utfør valgte handlinger</button></div>':'')+'<p class="legend">Avvik med samme filnavn overskrives ikke automatisk. De må kontrolleres først.</p>');if($('#executeSync'))$('#executeSync').onclick=executeSync}async function executeSync(){const picks=[...document.querySelectorAll('.syncPick:checked')].map(x=>Number(x.dataset.i)),actions=window.__iansSyncActions||[];if(!picks.length)return setStatus('Ingen synkhandlinger valgt.');if(!confirm('Utføre '+picks.length+' valgte synkhandlinger?'))return;$('#executeSync').disabled=true;let done=0;try{for(const i of picks){const a=actions[i];if(!a||a.dir==='conflict')continue;const dst=a.dir==='lr'?state.right.handle:state.left.handle;setStatus('Synkroniserer '+(done+1)+'/'+picks.length+' · '+a.name);await copyEntry(a.item.handle,dst,a.name);done++}await Promise.all([refresh('left'),refresh('right')]);closeDialog();setStatus('Synkronisering ferdig · '+done+' handlinger utført.')}catch(e){setStatus('Synkronisering stoppet: '+e.message);$('#executeSync').disabled=false}}
'''
    s=s[:a]+sync+s[b+1:]
p.write_text(s)
