from pathlib import Path
p=Path('tools/dinner-planner/index.html')
s=p.read_text()
# Cuisine selector
s=s.replace('<label><input type="checkbox" value="Thai" checked> Thai</label>','<label><input type="checkbox" value="Europeisk" checked> Europeisk</label><label><input type="checkbox" value="Italiensk"> Italiensk</label><label><input type="checkbox" value="Britisk"> Britisk</label><label><input type="checkbox" value="Amerikansk"> Amerikansk</label>')
# Add extras and budget after priority selector
needle='<select id="priority"><option value="Sunt og økonomisk">Sunt + økonomisk</option><option value="Ekstra sunt">Ekstra sunt</option><option value="Mest økonomisk">Mest økonomisk</option></select>'
insert=needle+'<label>Ukens matbudsjett (kr)</label><input id="weeklyBudget" type="number" min="0" max="20000" step="100" value="1800" placeholder="F.eks. 1800"><p class="muted">IANS bruker budsjettet som styring, men viser ikke påståtte live butikkpriser.</p><label>Ekstra denne uken</label><div class="checks extras"><label><input type="checkbox" value="Dessert"> 🍰 Dessert</label><label><input type="checkbox" value="Boller/bakst"> 🥐 Boller / bakst</label></div>'
if needle in s and 'id="weeklyBudget"' not in s:s=s.replace(needle,insert,1)
# AI request payload
old='cuisines,pantry:pantry.value,favorites:favorites(),image:imageData'
new="cuisines,pantry:pantry.value,favorites:favorites(),image:imageData,weeklyBudget:+weeklyBudget.value,extras:[...document.querySelectorAll('.extras input:checked')].map(x=>x.value)"
s=s.replace(old,new)
# Add extras + budget + savings ideas to AI rendering before shopping list
oldseg="+'</div><h2>Handleliste</h2><div class=\"shopping\">'"
newseg="+'</div>'+(x.extras?.length?'<h2>🍰 Bonus · dessert & bakst</h2><div class=\"days\">'+x.extras.map((m,i)=>'<div class=\"meal\"><h3>'+esc(m.name)+'</h3><div class=\"tags\">'+esc(m.cuisine||'')+' · '+(m.tags||[]).map(t=>'#'+esc(t)).join(' ')+'</div><div class=\"recipe\"><b>Ingredienser:</b> '+(m.ingredients||[]).map(esc).join(', ')+'<br><b>Slik gjør du:</b><ol>'+(m.steps||[]).map(st=>'<li>'+esc(st)+'</li>').join('')+'</ol>'+(m.tip?'<b>Tips:</b> '+esc(m.tip):'')+'</div></div>').join('')+'</div>':'')+(x.budget?'<h2>💰 Ukesbudsjett</h2><div class=\"tips\"><b>'+(x.budget.weekly?esc(x.budget.weekly)+' kr':'Ingen sum satt')+'</b><br>'+esc(x.budget.strategy||'')+'<br>'+(x.budget.stayOnTrack||[]).map(t=>'• '+esc(t)+'<br>').join('')+'</div>':'')+(x.savingIdeas?.length?'<h2>💡 Smarte sparegrep</h2><div class=\"days\">'+x.savingIdeas.map(i=>'<div class=\"meal\"><h3>'+esc(i.title)+'</h3><div class=\"recipe\">'+esc(i.text)+'<br><b>Potensial:</b> '+esc(i.monthlyPotential||'Avhenger av priser og forbruk.')+'</div></div>').join('')+'</div>':'')+'<h2>Handleliste</h2><div class=\"shopping\">'"
if oldseg in s:s=s.replace(oldseg,newseg,1)
# Local planner: remove Thai entries and add selected new cuisines
start="function localPlan(){const pool="
if start in s:
    a=s.index(start);b=s.index("function pdf(lang){",a)
    local=r'''function localPlan(){const pool=[['Chicken Adobo','Filippinsk'],['Pork Giniling','Filippinsk'],['Chicken Tinola','Filippinsk'],['Laks med poteter','Nordisk'],['Kjøttkaker og poteter','Nordisk'],['Kyllingform','Nordisk'],['Kyllinggryte med grønnsaker','Europeisk'],['Linsegryte','Europeisk'],['Ovnsbakt svin','Europeisk'],['Spaghetti Bolognese','Italiensk'],['Kylling pasta','Italiensk'],['Minestrone','Italiensk'],['Cottage Pie','Britisk'],['Fish Pie','Britisk'],['Sausage & Mash','Britisk'],['Chicken Tacos','Amerikansk'],['Homemade Burgers','Amerikansk'],['Chicken & Rice Bowl','Amerikansk']];let n=+days.value,cuis=[...document.querySelectorAll('.checks:not(.extras) input:checked')].map(x=>x.value),avail=pool.filter(x=>cuis.includes(x[1]));if(!avail.length)avail=pool.filter(x=>x[1]==='Nordisk');avail.sort(()=>Math.random()-.5);let plan=[];for(let i=0;i<n;i++)plan.push({day:i+1,name:avail[i%avail.length][0],cuisine:avail[i%avail.length][1],tags:['enkel'],ingredients:['Se oppskrift / tilpass etter hva dere har'],steps:['Tilbered retten med vanlige, trygge kokemetoder.'],tip:'Bruk opp råvarer dere allerede har først.'});let extras=[];if(document.querySelector('.extras input[value="Dessert"]')?.checked)extras.push({day:'Bonus',name:'Eplecrumble',cuisine:'Dessert',tags:['dessert'],ingredients:['epler','havregryn','hvetemel','smør','sukker','kanel'],steps:['Skjær epler i biter.','Lag smuldredeig.','Bak til gyllen.'],tip:'Bruk epler som må spises.'});if(document.querySelector('.extras input[value="Boller/bakst"]')?.checked)extras.push({day:'Bonus',name:'Hjemmelagde havreboller',cuisine:'Bakst',tags:['bakst'],ingredients:['hvetemel','havregryn','gjær','melk','smør','salt'],steps:['Lag deig.','Hev.','Form og etterhev.','Stek til gylne.'],tip:'Frys ned og ta opp etter behov.'});current={n,a:+adults.value,c:+children.value,meals:plan,extras,shopping:[],budget:{weekly:+weeklyBudget.value,strategy:'Bruk det dere har først, fordel innkjøpet på planlagte middager og hold en liten buffer.',stayOnTrack:['Handle med liste.','Sammenlign kilopris.','Planlegg rester.']},savingIdeas:[{title:'Bak selv',text:'Hjemmebakt brød og boller kan bli rimeligere enn ferdigkjøpt når du baker flere om gangen.',monthlyPotential:'Avhenger av hvor mye dere ellers kjøper.'},{title:'Strekk kjøttdeigen',text:'Bruk gulrot, bønner eller linser i sauser og gryter.',monthlyPotential:'Kan gi flere porsjoner per pakke.'},{title:'Planlagt restemat',text:'Gjør rester til lunsj, wok, suppe eller omelett.',monthlyPotential:'Mindre matsvinn over tid.'}],savingTips:['Sjekk kjøleskap og fryser før du handler.'],cookingTips:['Planlegg rester inn i neste dags måltid.']};renderAI()}'''
    s=s[:a]+local+s[b:]
# PDF V3: include extras in recipe booklet and budget/savings sections
s=s.replace("function pdf(lang){if(!current)return;const {jsPDF}=window.jspdf", "function pdf(lang){if(!current)return;const pdfMeals=[...(current.meals||[]),...(current.extras||[])];const {jsPDF}=window.jspdf")
s=s.replace("for(const m of current.meals||[]){page();section('🍽'", "for(const m of pdfMeals){page();section('🍽'")
# add budget section before footer marker if present
marker='// Footer on every page'
extra="""if(current.budget||current.savingIdeas?.length){page();section('💰',en?'BUDGET & SAVING IDEAS':'BUDSJETT & SPARETIPS');if(current.budget){line((en?'Weekly budget: ':'Ukesbudsjett: ')+(current.budget.weekly||0)+' kr',11,true);line(current.budget.strategy||'',10);for(const t of current.budget.stayOnTrack||[])line('• '+t,10)}for(const i of current.savingIdeas||[]){y+=3;line(i.title,10,true);line(i.text,9);if(i.monthlyPotential)line((en?'Potential: ':'Potensial: ')+i.monthlyPotential,9)}}\n"""
if marker in s and "BUDSJETT & SPARETIPS" not in s:s=s.replace(marker,extra+marker,1)
p.write_text(s)
