from pathlib import Path
p=Path('tools/dinner-planner/index.html')
s=p.read_text()
# Add styles for budget cockpit
s=s.replace('.tips{border-left:3px solid var(--cyan);padding-left:14px}', '.tips{border-left:3px solid var(--cyan);padding-left:14px}.budgetbar{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:12px 0 18px}.metric{background:#04111d;border:1px solid #24445f;border-radius:13px;padding:12px}.metric b{display:block;font-size:1.35rem;margin-top:4px}.metric.good{border-color:#1e7b5a}.metric.warn{border-color:#8c6a26}.pricegrid{display:grid;grid-template-columns:1fr auto auto;gap:7px;align-items:center;margin-top:10px}.pricegrid input{width:90px;padding:7px}.statuspill{display:inline-block;border-radius:999px;padding:5px 9px;font-size:12px;font-weight:800;background:#123047}.statuspill.good{background:#123d2f;color:#8cf0bf}.statuspill.warn{background:#4a3513;color:#ffd68a}')
s=s.replace('@media(max-width:760px){.top', '@media(max-width:760px){.budgetbar{grid-template-columns:1fr 1fr}.pricegrid{grid-template-columns:1fr 82px auto}.top')
# Add budget preview target under budget field
needle='<p class="muted">IANS bruker budsjettet som styring, men viser ikke påståtte live butikkpriser.</p>'
insert=needle+'<div id="budgetMini" class="muted">Prisoverslag vises etter at planen er laget.</div>'
s=s.replace(needle,insert,1)
# Insert estimator functions before aiBtn
marker='aiBtn.onclick=async()=>'
addon=r'''const priceCatalog={"kyllingfilet":149,"kylling":129,"svinekjøttdeig":79,"kjøttdeig":89,"svinefilet":119,"laks":159,"kjøttkaker":89,"poteter":39,"jasminris":59,"ris":49,"nudler":24,"pasta":25,"brokkoli":29,"gulrot":24,"paprika":39,"tomat":35,"løk":25,"hvitløk":19,"ingefær":24,"kokosmelk":28,"soyasaus":34,"eddik":24,"lime":12,"sitron":12,"melk":25,"smør":49,"hvetemel":29,"havregryn":29,"gjær":9,"sukker":29,"epler":39,"egg":49,"ost":79,"rømme":29,"mais":19,"salsa":29,"tortilla":35,"taco":35};
function normPriceName(x){return String(x||'').toLowerCase().replace(/[0-9.,]+\s*(kg|g|l|ml|stk|pk|pakke|poser?)/g,'').trim()}
function guessPrice(item){let n=normPriceName(item);for(const [k,v] of Object.entries(priceCatalog))if(n.includes(k))return v;return 35}
function pantryHas(item){let p=pantry.value.toLowerCase(),n=normPriceName(item);return n.length>2&&p.includes(n.split(' ')[0])}
function buildPriceEstimate(){if(!current)return;let rows=(current.shopping||[]).map((x,i)=>({i,item:x.item,quantity:x.quantity||'',price:Number(x.estimatedPrice)||guessPrice(x.item),owned:pantryHas(x.item)}));current.priceRows=rows;renderBudgetCockpit()}
function estimateTotal(){return (current?.priceRows||[]).reduce((a,x)=>a+(x.owned?0:Number(x.price)||0),0)}
function renderBudgetCockpit(){if(!current)return;let budget=Number(weeklyBudget?.value||current.budget?.weekly||0),total=Math.round(estimateTotal()),left=budget-total,ok=!budget||left>=0;let html='<h2>💰 Budsjettkontroll før PDF</h2><div class="budgetbar"><div class="metric"><span>Ukesbudsjett</span><b>'+budget+' kr</b></div><div class="metric"><span>Estimert handlekurv</span><b>'+total+' kr</b></div><div class="metric '+(ok?'good':'warn')+'"><span>'+(ok?'Til overs':'Over budsjett')+'</span><b>'+Math.abs(left)+' kr</b></div><div class="metric '+(ok?'good':'warn')+'"><span>Status</span><b style="font-size:1rem">'+(ok?'✓ Innenfor':'⚠ Juster planen')+'</b></div></div><p class="muted">Prisene er IANS-estimater, ikke live hyllepriser. Du kan korrigere hver pris før PDF genereres.</p><div class="pricegrid">';for(const x of current.priceRows||[])html+='<span>'+esc(x.item)+(x.quantity?' · '+esc(x.quantity):'')+(x.owned?' <span class="statuspill good">har hjemme</span>':'')+'</span><input type="number" min="0" step="1" value="'+x.price+'" data-price="'+x.i+'"><label style="margin:0;font-weight:500"><input type="checkbox" data-owned="'+x.i+'" '+(x.owned?'checked':'')+' style="width:auto"> har</label>';html+='</div><button class="btn alt" id="recalcBudget">↻ Regn budsjett på nytt</button>';if(!ok)html+='<button class="btn" id="budgetOptimize">✦ Vis spareforslag</button>';let old=document.getElementById('budgetCockpit');if(!old){old=document.createElement('div');old.id='budgetCockpit';out.appendChild(old)}old.innerHTML=html;document.querySelectorAll('[data-price]').forEach(el=>el.onchange=()=>{let r=current.priceRows[+el.dataset.price];r.price=Number(el.value)||0;renderBudgetCockpit()});document.querySelectorAll('[data-owned]').forEach(el=>el.onchange=()=>{current.priceRows[+el.dataset.owned].owned=el.checked;renderBudgetCockpit()});let rb=document.getElementById('recalcBudget');if(rb)rb.onclick=renderBudgetCockpit;let bo=document.getElementById('budgetOptimize');if(bo)bo.onclick=()=>{let over=Math.max(0,total-budget),tips=[];if(over){tips.push('Bytt én dyr kjøtt-/fiskemiddag med egg, suppe, linser eller restemiddag.');tips.push('Bruk grønnsaker dere allerede har før dere kjøper nye varianter.');tips.push('Velg butikkens rimelige merkevarer og sammenlign kilopris.');tips.push('Bak brød/boller hjemme hvis dere ellers kjøper flere brød i uken.');tips.push('Frys porsjoner og planlegg én restelunsj eller restemiddag.')}alert('For å hente inn ca. '+over+' kr:\n\n• '+tips.join('\n• '))};if(budgetMini)budgetMini.textContent='Estimert handlekurv: '+total+' kr av '+budget+' kr · '+(ok?'innenfor budsjett':'over budsjett')}
'''
if marker in s and 'function buildPriceEstimate()' not in s:s=s.replace(marker,addon+marker,1)
# After renderAI output creation, run estimator asynchronously
needle2="<button class=\"btn alt\" onclick=\"pdf('en')\">Download PDF · English</button>'}"
if needle2 in s:
    s=s.replace(needle2,"<button class=\"btn alt\" onclick=\"pdf('en')\">Download PDF · English</button>';setTimeout(buildPriceEstimate,0)}",1)
# Ensure local plan also generates a shopping list from extras/meals when empty
old="current={n,a:+adults.value,c:+children.value,meals:plan,extras,shopping:[],budget:"
new="let shopNames=[...new Set([...plan,...extras].flatMap(m=>m.ingredients||[]).filter(x=>!String(x).startsWith('Se oppskrift')))];current={n,a:+adults.value,c:+children.value,meals:plan,extras,shopping:shopNames.map(item=>({item,quantity:'1 passende pakke',category:'Handleliste'})),budget:"
s=s.replace(old,new)
# Put budget estimate into PDF cover and budget page when available
s=s.replace("d.text('🍽  '+current.n", "if(current.priceRows?.length){let et=Math.round(estimateTotal()),wb=Number(weeklyBudget?.value||0);d.setTextColor(120,210,255);d.setFontSize(12);d.text('💰  '+(en?'Estimated shopping: ':'Estimert handel: ')+et+' kr  ·  '+(en?'Budget: ':'Budsjett: ')+wb+' kr',M,78)}d.setTextColor(255);d.text('🍽  '+current.n")
s=s.replace("if(current.budget){line((en?'Weekly budget: '", "if(current.budget){if(current.priceRows?.length){line((en?'Estimated shopping: ':'Estimert handlekurv: ')+Math.round(estimateTotal())+' kr',11,true);line((en?'Budget status: ':'Budsjettstatus: ')+(estimateTotal()<=Number(weeklyBudget?.value||0)?(en?'Within budget':'Innenfor budsjett'):(en?'Over budget':'Over budsjett')),10)}line((en?'Weekly budget: '")
p.write_text(s)
