import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../assets/ians-home/costs.js',import.meta.url),'utf8');
const {parseCosts}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const now=new Date('2026-09-24T12:00:00Z');
const valid={status:'available',currency:'NOK',periodStart:'2026-09-01',periodEnd:'2026-09-23',updatedAt:'2026-09-24T09:00:00Z',staticWebApps:{iansNok:0,sogodNok:0},azureTotalNok:0.02,includes:['IANS Static Web App','SOGOD Static Web App','Andre Azure-tjenester kan inngå'],excludes:['Domener','OpenAI og andre eksterne AI-tjenester']};
test('accepts separate Static Web App costs and Azure aggregate',()=>{const parsed=parseCosts(valid,now);assert.equal(parsed.staticWebApps.iansNok,0);assert.equal(parsed.staticWebApps.sogodNok,0);assert.equal(parsed.azureTotalNok,0.02)});
test('accepts genuine zero costs without fabricating missing values',()=>{assert.equal(parseCosts({...valid,azureTotalNok:0},now).azureTotalNok,0);for(const azureTotalNok of [null,-1,'0.02',Infinity,undefined])assert.equal(parseCosts({...valid,azureTotalNok},now),null);assert.equal(parseCosts({status:'unavailable'},now),null)});
test('rejects invalid Static Web App costs or an aggregate below their sum',()=>{for(const patch of [{staticWebApps:null},{staticWebApps:{iansNok:-1,sogodNok:0}},{staticWebApps:{iansNok:0,sogodNok:'0'}},{azureTotalNok:0,staticWebApps:{iansNok:0.01,sogodNok:0}},{currency:'USD'}])assert.equal(parseCosts({...valid,...patch},now),null)});
test('requires honest dates and scope',()=>{for(const patch of [{periodEnd:'2026-08-30'},{periodStart:'2026-02-30'},{updatedAt:'2026-10-01T00:00:00Z'},{updatedAt:'2026-09-24'},{includes:[]},{periodEnd:'2026-09-25'}])assert.equal(parseCosts({...valid,...patch},now),null)});
test('marks data over 72 hours old',()=>assert.equal(parseCosts({...valid,periodEnd:'2026-09-19',updatedAt:'2026-09-20T09:00:00Z'},now).stale,true));
