const {TableClient}=require('@azure/data-tables');
const crypto=require('crypto');
const {hasAccess}=require('../sameie-access/index.js');

const OWNER='henrik.bergfjord@outlook.com';
const T={sameie:'IansSameier',units:'IansSameieUnits',people:'IansSameiePeople',members:'IansSameieMembers',inspections:'IansSameieInspections'};
function json(status,body){return{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'},body:JSON.stringify(body)}}
function clean(v,n=254){return String(v||'').trim().slice(0,n)}
function cs(){return process.env.IANS_BOOKING_STORAGE||process.env.AzureWebJobsStorage}
function table(name){const c=cs();if(!c)throw new Error('Storage er ikke konfigurert');return TableClient.fromConnectionString(c,name)}
function principal(req){try{const r=req.headers['x-ms-client-principal'];return r?JSON.parse(Buffer.from(r,'base64').toString('utf8')):null}catch{return null}}
function emailOf(p){return clean(p&&p.userDetails).toLowerCase()}
function key(v){return crypto.createHash('sha256').update(String(v||'').toLowerCase()).digest('hex').slice(0,40)}
function safeRow(v){return clean(v,100).replace(/[\\/#?\u0000-\u001f\u007f]/g,'-')}
async function ensure(t){await t.createTable().catch(e=>{if(e.statusCode!==409)throw e})}
async function canRead(email,sameie){if(email===OWNER)return true;return !!(await hasAccess(email,sameie,'yearwheel')).approved||!!(await hasAccess(email,sameie,'sprinkler')).approved||!!(await hasAccess(email,sameie,'fire')).approved}
async function canAdmin(email,sameie){if(email===OWNER)return true;const a=await hasAccess(email,sameie);return !!a.approved&&['owner','styreleder','admin'].includes(String(a.role||'').toLowerCase())}
async function countPartition(tc,p){let n=0;for await(const _ of tc.listEntities({queryOptions:{filter:`PartitionKey eq '${p}'`}}))n++;return n}
async function seedSameie(sameie,email){const tc=table(T.sameie);await ensure(tc);try{return await tc.getEntity('sameie',sameie)}catch(e){if(e.statusCode!==404)throw e;if(sameie!=='straumsfjellet-panorama')return null;const now=new Date().toISOString();const entity={partitionKey:'sameie',rowKey:sameie,name:'Straumsfjellet Panorama Sameie',displayName:'Straumsfjellet Panorama',address:'Straumsfjellvegen 5–9',city:'5353 Straume',orgNo:'',unitCount:204,status:'active',modules:'sprinkler,fire,yearwheel,maintenance',profileImageUrl:'',createdAt:now,createdBy:email||'bootstrap',updatedAt:now,updatedBy:email||'bootstrap'};await tc.createEntity(entity);return entity}}
module.exports=async function(context,req){try{const method=req.method||'GET',p=principal(req),email=emailOf(p);if(!email)return context.res=json(401,{ok:false,error:'Microsoft-innlogging kreves.'});const b=req.body||{},sameie=clean(req.query.sameie||b.sameie||'straumsfjellet-panorama',80);if(!sameie)return context.res=json(400,{ok:false,error:'Mangler sameie.'});const profile=await seedSameie(sameie,email);if(!profile)return context.res=json(404,{ok:false,error:'Sameiet finnes ikke.'});if(!await canRead(email,sameie))return context.res=json(403,{ok:false,error:'Du har ikke godkjent tilgang til dette sameiet.'});
if(method==='GET'){const action=clean(req.query.action||'dashboard',40);if(action==='profile'||action==='dashboard'){const units=table(T.units),people=table(T.people),members=table(T.members),insp=table(T.inspections);await Promise.all([ensure(units),ensure(people),ensure(members),ensure(insp)]);const [unitCount,peopleCount,memberCount,inspectionCount]=await Promise.all([countPartition(units,sameie),countPartition(people,sameie),countPartition(members,sameie),countPartition(insp,sameie)]);return context.res=json(200,{ok:true,sameie:{id:profile.rowKey,name:profile.name,displayName:profile.displayName,address:profile.address,city:profile.city,orgNo:profile.orgNo,unitCount:Number(profile.unitCount||0),status:profile.status,modules:String(profile.modules||'').split(',').filter(Boolean),profileImageUrl:profile.profileImageUrl||''},stats:{registeredUnits:unitCount,people:peopleCount,members:memberCount,inspections:inspectionCount},permissions:{admin:await canAdmin(email,sameie)},user:{email}})}
if(action==='members'){if(!await canAdmin(email,sameie))return context.res=json(403,{ok:false,error:'Kun styreleder/admin kan se medlemsregisteret.'});const tc=table(T.members);await ensure(tc);const rows=[];for await(const e of tc.listEntities({queryOptions:{filter:`PartitionKey eq '${sameie}'`}}))rows.push({id:e.rowKey,name:e.name||'',email:e.email||'',role:e.role||'',services:String(e.services||'').split(',').filter(Boolean),status:e.status||'',createdAt:e.createdAt||''});return context.res=json(200,{ok:true,members:rows})}
if(action==='units'){const tc=table(T.units);await ensure(tc);const rows=[];for await(const e of tc.listEntities({queryOptions:{filter:`PartitionKey eq '${sameie}'`}}))rows.push({id:e.rowKey,entrance:e.entrance||'',unitCode:e.unitCode||'',apartmentNo:e.apartmentNo||'',address:e.address||'',status:e.status||'active'});return context.res=json(200,{ok:true,units:rows})}
if(action==='inspections'){const tc=table(T.inspections);await ensure(tc);const rows=[];for await(const e of tc.listEntities({queryOptions:{filter:`PartitionKey eq '${sameie}'`}}))rows.push({id:e.rowKey,unitId:e.unitId||'',year:Number(e.year||0),type:e.type||'',status:e.status||'',date:e.date||'',source:e.source||'',notes:e.notes||''});rows.sort((a,b)=>b.year-a.year||String(b.date).localeCompare(String(a.date)));return context.res=json(200,{ok:true,inspections:rows})}
return context.res=json(400,{ok:false,error:'Ukjent handling.'})}
if(method==='POST'){if(!await canAdmin(email,sameie))return context.res=json(403,{ok:false,error:'Kun styreleder/admin kan endre registeret.'});const type=clean(b.type,30),now=new Date().toISOString();if(type==='member'){const target=clean(b.email,254).toLowerCase(),name=clean(b.name,120),role=clean(b.role,50)||'Styremedlem',services=Array.isArray(b.services)?b.services.filter(x=>['sprinkler','fire','yearwheel','maintenance'].includes(x)):[];if(!target.includes('@')||!name)return context.res=json(400,{ok:false,error:'Navn og e-post må fylles ut.'});const tc=table(T.members);await ensure(tc);await tc.upsertEntity({partitionKey:sameie,rowKey:key(target),name,email:target,role,services:services.join(','),status:'active',createdAt:now,updatedAt:now,updatedBy:email},'Merge');return context.res=json(201,{ok:true})}
if(type==='unit'){const entrance=clean(b.entrance,30),unitCode=clean(b.unitCode,30),apartmentNo=clean(b.apartmentNo,30),address=clean(b.address,160);if(!entrance||!unitCode)return context.res=json(400,{ok:false,error:'Oppgang og bruksenhet må fylles ut.'});const id=safeRow(`${entrance}-${unitCode}`.toLowerCase());const tc=table(T.units);await ensure(tc);await tc.upsertEntity({partitionKey:sameie,rowKey:id,entrance,unitCode,apartmentNo,address,status:'active',updatedAt:now,updatedBy:email},'Merge');return context.res=json(201,{ok:true,id})}
if(type==='inspection'){const unitId=safeRow(b.unitId),year=Number(b.year),inspectionType=clean(b.inspectionType||b.controlType,50),status=clean(b.status,40)||'completed',date=clean(b.date,20),source=clean(b.source,160),notes=clean(b.notes,1000);if(!unitId||!year||!inspectionType)return context.res=json(400,{ok:false,error:'Bolig, år og kontrolltype må fylles ut.'});const tc=table(T.inspections);await ensure(tc);const id=safeRow(`${year}-${inspectionType}-${unitId}-${date||'unknown'}`.toLowerCase());await tc.upsertEntity({partitionKey:sameie,rowKey:id,unitId,year, type:inspectionType,status,date,source,notes,createdAt:now,createdBy:email},'Replace');return context.res=json(201,{ok:true,id})}
if(type==='profile'){const tc=table(T.sameie);await ensure(tc);const current=await tc.getEntity('sameie',sameie);for(const f of ['displayName','address','city','orgNo','profileImageUrl'])if(b[f]!==undefined)current[f]=clean(b[f],200);if(b.unitCount!==undefined)current.unitCount=Math.max(0,Number(b.unitCount)||0);current.updatedAt=now;current.updatedBy=email;await tc.updateEntity(current,'Replace');return context.res=json(200,{ok:true})}
return context.res=json(400,{ok:false,error:'Ukjent datatype.'})}
return context.res=json(405,{ok:false,error:'Metoden støttes ikke.'})}catch(e){context.log.error(e);context.res=json(500,{ok:false,error:'SameieNett-kjernen kunne ikke behandle forespørselen.'})}};